### ISSUE TITLE
Not working with browserify

### ISSUE THREAD

**Issue by ryanzec** [spoike/refluxjs#129]
While browserify compiles this library fine, when I try to use it, it get this in the console:

```Uncaught Error: Cannot find module '../src' ```

and when I look at the browserify generated code, I see stuff like this:

```javascript
},{"../src":undefined,"./utils":174}],169:[function(require,module,exports){
```

Why is this not working (using version 0.1.15)?

**Comment by mschipperheyn** [comment]
This seems to work for me to prevent gulp from choking. Although it still requires me to reference a bower reflux file since reflux is no longer built. Hopefully this bug will be resolved soon. This was my first experience w reflux. It's not really a great way to get started with it. 

	var config = {
		dependencies: [
		'react',,
		'react/addons',
		'react-router',
		'reflux'
		],
		BUILD:'./build',
		DIST:'./dist',
		development:true
	};

	gulp.task('build-vendor', function(){

		var vendorsBundler = browserify({
		  debug: true, 
		  require: config.dependencies,
		  noParse:[
			require.resolve('reflux')
		  ]
		});
	
		vendorsBundler.bundle()
		  .on('error', gutil.log)
		  .pipe(source('scripts/vendors/vendors.js'))
		  .pipe(gulpif(!config.development, streamify(uglify())))
		  .pipe(gulp.dest(config.BUILD)); 

	});

	gulp.task('build-app', function(){

	  /* First we define our application bundler. This bundle is the
		 files you create in the "app" folder */
		var appBundler = browserify({
			entries: ['./src/scripts/app.jsx'], // The entry file, normally "main.js"
			transform: [reactify],
			debug: config.development,
			extensions: ['.jsx'],
			cache: {}, packageCache: {}, fullPaths: true
		});

		(config.development ? config.dependencies : []).forEach(function (dep) {
			appBundler.external(dep);
		});
  
		appBundler.bundle()
		  .pipe(source('scripts/app.jsx'))
		  .pipe(rename('scripts/app.js'))
		  .pipe(gulpif(!config.development, streamify(uglify())))
		  .pipe(gulp.dest(config.BUILD))
		  .pipe(gulpif(config.development, livereload()));
	});

**Comment by mschipperheyn** [comment]
One last thing I noticed here is that the require('Reflux') dependency is case sensitive. Just for people working their way through this stuff.

Please fix this issue asap. I don't think you appreciate just how sucky this issue really is.

**Comment by spoike** [comment]
Actually it worked to include reflux if you referenced it by relative path to the installed npm package's main file `node_modules/reflux/src/index.js` like this:

```javascript
var gulp = require('gulp')
    browserify = require('browserify'),
    source = require("vinyl-source-stream");

gulp.task('scripts-vendor', function() {
    return browserify()
        .require("./node_modules/reflux/src/index.js", { expose: 'reflux'})
        .bundle()
        .pipe(source("vendor.js"))
        .pipe(gulp.dest("./dist"));
});

gulp.task('scripts-app', function() {
    return browserify("./application.js")
        .external("reflux")
        .bundle()
        .pipe(source("app.js"))
        .pipe(gulp.dest("./dist"));
});

gulp.task('default', ['scripts-vendor', 'scripts-app']);
```

Fixed the issue on my side and it should work by doing `.require("reflux")` instead now, as many have lamented over. I.e. for the code example above:

```javascript
gulp.task('scripts-vendor', function() {
    return browserify()
        .require("./node_modules/reflux/src/index.js", { expose: 'reflux'})
        .bundle()
        .pipe(source("vendor.js"))
        .pipe(gulp.dest("./dist"));
});
```

Sorry for the time it took to fix this.
