### ISSUE TITLE
Benifits of Flux

### ISSUE THREAD

**Issue by iammerrick** [spoike/refluxjs#153]
One of the primary touted points of Flux is the ability to drop in a console.log at your dispatchr and be able to see *everything* that is happening in your app to trace down bugs. It seems this ability is lost with reflux. Does reflux have the ability to hook into all the events for a given store or reflux in general to reproduce bugs caused by store state?

**Comment by Dharmoslap** [comment]
See http://stackoverflow.com/questions/30359498/reflux-actions-global-debugging
