### ISSUE TITLE
Triggering discrete actions (via namespace or something similar) from a store?

### ISSUE THREAD

**Issue by kwhitaker** [spoike/refluxjs#158]
It's entirely possible that this is an architecture question, and not a functionality question.  I'm coming from a backbone background, where we can namespace events coming out of a model:
`
this.trigger('namespace:eventName', args);
`

That namespace allows me to have various parts of an app share a model, but only take an action if they are listening for that particular eventName and namespace.  Is there something like this in Reflux, or am I missing something in the inherent architecture here?  All of the examples have a store firing a `trigger` event, with the entirety of its data.

For example, if I have an `AppStore`, and it hold the states for a few things (modal visibility, which menu is open).  My modal component only needs to care about whether there's some modal data, my menus only which menu is active, etc.
Thanks.

**Comment by lucsky** [comment]
+1

I would love to be able to distinguish different store update events which in my case cannot be done by simply using multiple stores. Simplified to the max, my use case is that I have two integer values which can vary independently, both increase, both decrease, increase/decrease or decrease/increase, and each of these case would ideally trigger a different event. Right now I'm just adding a parameter to the `this.trigger()` call but it obviously forces to test it on the handler side, which is ugly and which is what Reflux actions were supposed to prevent on the other side of the store :)

**Comment by yonatanmn** [comment]
@lucsky if you have a simple case, it just easier to listen to the store without registering an Action. 
The mechanics are otherwise the same (I think...)

**Comment by jesstelford** [comment]
I found this discussion exceptionally informative. Thanks to everyone involved.

As a result, I have created a mixin for handling the example @yonatanmn gave:

```javascript
// triggerable.js
module.exports = {
  init: function() {
    if (!this.triggerables) {
      return;
    }

    // attach the given action names as actions on the store
    this.triggerables.forEach(
      function attachAction(actionName) {
        this[actionName] = Reflux.createAction();
      },
      this
    );
  }
};
```

Usage:

```javascript
// myStore.js
var Reflux = require('reflux'),
    triggerableMixin = require('./triggerable');

module.exports = Reflux.createStore({

  mixins: [triggerableMixin],

  listenables: {
    something: Reflux.createAction()
  },

  // The mixin turns each of these into a named action on the store.
  triggerables: [
    'somethingHappened'
  ],

  onSomething: function() {
    this.somethingHappened.trigger('foo');
  }

});
```

Later, in a component, etc, you can listen to this event:

```
var myStore = require('./myStore.js');

myStore.somethingHappened.listen(function(what) {
  console.log(what + ' happened');
});
```

Hopefully this helps someone else in the future who is struggling with the same situation.

**Comment by yonatanmn** [comment]
Looks cool! I'll give it a try

**Comment by yonatanmn** [comment]
Hi @spoike , I'm going to add Reflux option to [react-webpack yeoman generator] (https://github.com/newtriks/generator-react-webpack), and I think I will add @jesstelford's mixin. 
What do you think about adding it to Reflux directly? it will be much more elegant (and I believe also useful.)

**Comment by jesstelford** [comment]
@yonatanmn / @spoike I have created an npm module out of my code from above (complete with a couple of enhancements, tests & docs): https://www.npmjs.com/package/reflux-triggerable-mixin

```js
$ npm install --save reflux-triggerable-mixin
```

**Comment by apreg** [comment]
Here is another example: imagine there are multiple auction cards in a gridview. Each card represents a different auction of course. The current price and some other attributes of the auction is coming from server through websockets. There is an AuctionStore which provides live data by trigger(). The AuctionCards connect to this store. The problem is this way every AuctionCard component will show the last data received. I could create somehow multiple actions dynamically per AuctionCard but it feels hacky and I don't know how to do that yet. What about one store per AuctionCard?

**Comment by AnSavvides** [comment]
@jesstelford mixin works really nicely :)
