### ISSUE TITLE
feature idea

### ISSUE THREAD

**Issue by gedw99** [spoike/refluxjs#175]
i work with dag and data flows

react and reflux are great. i am happy that the web world is started to embrace forward dag and reflux especially embracing map / reduce (for / join) primitves.

I would like to build a Web IDE for Reflux that allows a user to visualise the graph or DAG.
It would be self instrumenting and so you could "see2´" the code.
then i wish to visualise the code DAG in 3D
then i want to put in a layer that allows DAG edges to cross partitions ( web workers or over ip ports)

then to the data. each node in the graph needs streaming interface. I bit like an excel spreadsheet.
then on top of that computed values out of the stream essentially become parametric streaming values throw the system.

this allows completely reactive applications to be built.

what i am describing is a bit like what noflo did. 
But i think that react and reflux people are now mre away about data flow and its just a mature to tooling it well to help people realise what can be done with it.
its a way to build real time distributed systems.
that allows: sensor fusion from DSP board level up to grid; machine learning with parametric values flowing through the system over time.

--

SO the Features needed for this ?
1. DSL described from the Javascript.
- so the graph can be real time described

2. instrumentation of the graph as it runs.
- this just requires an adapter pattern

**Comment by spoike** [comment]
I believe you can build a data flow diagram by simply analyzing the dependencies of the code. If you're doing simple commonjs modules (nodejs modules, browserify) you could just graph out all the require calls for each file.

A more advanced solution would to look at the AST that is built by the javascript interpreter.

Not sure what you mean with the features you need.
