### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by aarongreenlee** [spoike/refluxjs#178]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with refluxjs. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable refluxjs on @Sourcegraph by going to https://sourcegraph.com/github.com/spoike/refluxjs and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by spoike** [comment]
I've enabled refluxjs on sourcegraph
