### ISSUE TITLE
How best to seed store with data from server side?

### ISSUE THREAD

**Issue by schutterp** [spoike/refluxjs#182]
I have isomorphic react components that render serverside, but I haven't found a 'good' way to seed the stores in the browser with the state provided from the server.

In my app's initialization method on the client I am directly passing the state data to what should be a private update method on the store before rendering my react components.  Is there a best practice for accomplishing this?

**Comment by influx6** [comment]
You can create a stateData manager for each group of react components or create a global one, these will handle providing state data to the stores. And allows easy change and maintainability

**Comment by gpbl** [comment]
I'm using [express-state](https://github.com/yahoo/express-state) on the server and a [store mixin](https://github.com/spoike/refluxjs/pull/124#issuecomment-69107578) to rehydrate data in the store's state.

**Comment by schutterp** [comment]
Thanks for the replies!
