### ISSUE TITLE
how to new a store?

### ISSUE THREAD

**Issue by binlaniua** [spoike/refluxjs#186]
~

**Comment by spoike** [comment]
You don't need to instantiate a store with `new`. `createStore` does that for you.

```javascript
var store = Reflux.createStore({
  // continue definition here
});
```

**Comment by binlaniua** [comment]
```
var Store = Reflux.createStore({
});

var storeInstance = new Store(...}
```

because my each page have some same components, each them have same store, but different config in store

**Comment by influx6** [comment]
Every time you call 
```javascript
 Store.createStore({...}) 
```

A new object is automatic created for you so don't worry, even if your configuration are different, the stores won't class,as they are already unique objects

**Comment by binlaniua** [comment]
@influx6  thanks

**Comment by influx6** [comment]
@binlaniua you are welcome,it's God's grace ;)!
