### ISSUE TITLE
[Question] Async workflow

### ISSUE THREAD

**Issue by Cethy** [spoike/refluxjs#188]
I need some clarification on async management in Relfux :

I have :
- `AppComponent` with a `List`, and a `Form`
- `DataActions(load,update)`, `AppActions(displayList,displayForm)` and `FormActions(change,submit)`
- `DataStore(loadCompleted,updateCompleted)`, `AppStore()` and `FormStore()`

Workflow :
- 1. `AppComponent` displays the list when `DataStore.loadCompleted` trigger data loaded ;
- 2. the user trigger `AppActions.displayForm(item)` ;
- 3. `AppComponent` displays the form populated and all ;
- 4. the user trigger `FormActions.submit(old, new)` ;
- 5. `FormStore` receive a new state (`computing ...`) ; the form component is correctly updated ;
- 6. `FormStore` call `DataActions.update(old, new)` ; which will trigger `DataActions.updateCompleted()` when promise resolved
- 7. `DataStore` *must* call `AppActions.displayList()` ; which close the form component

While step 6 introduce a *totally fine* dependency between FormStore & DataActions (on FormStore side), step 7 introduce a **totally unacceptable** one (on DataStore side with AppActions).

The only workaround I found is to make AppStore listening to DataActions.updateCompleted and close any form opened but it's seems very weak to me (what if another part of the app can update data ?).

Any suggestions ?

**Comment by spoike** [comment]
AppComponent or Form may listen to actions too. In this example `DataActions.updateCompleted` too as a short circuit. There is no need for data stores to manipulate the UI other than giving feedback of changes to the data... the components should be able to manipulate the UI through their own state IMHO.

By the way Isn't it weird UX to just close the form without any feedback that the data has successfully updated (or has errored)?

**Comment by Cethy** [comment]
I treat all component states as store(s), to be able to rehydrate the UI at any state I want (page refresh/page sharing/demoing stuff). Is it a wrong approach ?

Also I kept the feedback store & component outside to simplify the problem : once I'm able to target an actual `formActions.submitCompleted` (or Failed) action, I will put a feedback on that :)

My problem look similar to @bericp1 in #177, but the tag use seems to me a little to heavy.

I'm looking in the use of a `joinTrailing`, if I join `FormActions.submit` & `DataActions.updateCompleted`, i have a safer way to catch the right action, but it looks over-complicated for what i'm trying to achieve. Any opinion on that ?

**Comment by Cethy** [comment]
I let it soak into my brain for a while and ... I got it all wrong :)

Either the UI is "single-user", in this case I don't have to worry for some dataStore.update triggering form other part of the app. 
Or the UI is "multi-user", and in this case the form should close right after user submit, and the "data update loading/finished" feedback should only rely on the dataStore.update. (like gmail works)

Problem solved. :)
