### ISSUE TITLE
Is there something like a postEmit?

### ISSUE THREAD

**Issue by stopachka** [spoike/refluxjs#190]
Hey there, I'm in a position where I get back a big blob, like this ->

```
blob = {
  foo: {..}
  bar: {..}
}
```

This will get fed into 2 stores

```
barStore

FooStore
  int: ->
     @listenTo(barStore, "onBar")

```

The actions I want to trigger are like so

1. First feed blob into FooStore, for it to take relevant parts
2. Second feed blob in BarStore, for it to take relevant parts
3. BarStore will then trigger FooStore again, giving it the most correct version of foos

This is done because sometimes the blob does not return all of the bars, so I want to store them separately.

The question is, how can I make this flow work?

I want to do something like 

```
Actions.gotBar = Reflux.createAction(sync: true)
Actions.gotFoo = Reflux.createAction(sync: true)

Actions.gotBar.postEmit Actions.gotFoo
```

**Comment by spoike** [comment]
You could create a `BlobStore` that can emit both actions seperately.

```coffeescript
Actions = Reflux.createActions ["gotBlob", "gotBar", "gotFoo"]

BlobStore = Reflux.createStore
  listenables: [Actions]
  onGotBlob: (blob) ->
    Actions.gotFoo(blob.foo) if blob.foo
    Actions.gotBar(blob.bar) if blob.bar
``´

Alternatively you could use child actions if you're not doing much processing of the blob. See PR #140 or https://github.com/spoike/refluxjs#asynchronous-actions

**Comment by stopachka** [comment]
perfect! Thanks spoike :+1:
