### ISSUE TITLE
Question: example of async promise using superagent

### ISSUE THREAD

**Issue by mschipperheyn** [spoike/refluxjs#194]
It would be nice if you could supply an example that uses the async promise you describe in the documentation in combination with superagent, a common library for async io interaction.

I also don't understand when to use preEmit and when to use listen

**Comment by bebraw** [comment]
Check the end of http://spoike.ghost.io/refluxjs-0-1-8/ for an async `preEmit` example (section `Async? Yes, we can!`). That might clear things up a bit.

With superagent it would look something like this:

```javascript
var ProductActions = Reflux.createActions({  
  'load',         // initiates the async load
  'loadComplete', // when the load is complete
  'loadError'     // when the load has failed
});

ProductActions.load.preEmit = function () {  
     // Perform the API call, get a promise
     request.get(...).end(function(err, res) {
         if(err) {return ProductActions.loadError(err);}
         ProductActions.loadComplete(res);
     });
};
```

**Comment by spoike** [comment]
There is also child actions which was implemented in #140. And described in the [README.md here](https://github.com/spoike/refluxjs#asynchronous-actions).

You can use it with [`superagent`](https://github.com/visionmedia/superagent) like this:

```javascript
var request = require('superagent'),
    productUrl = '...';

var ProductActions = Reflux.createActions({
  'load': {children: ['completed', 'failed']}
});

ProductActions.load.listen(function() {
  var thisAction = this;
  request.get(productUrl)
    .end(function(err, res) {
      if (err) { return thisAction.failed(err) }
      thisAction.completed(res);
    });
});
```

Difference between `listen` and `preEmit` is mostly that `preEmit` is called once every invocation of the action and it lets you **map the data** before the event is passed on to everyone that `listen`s to the action. In this case it won't matter much.

**Comment by gabro** [comment]
I faced the same issue and my solution was using a library ([superagent-bluebird-proimise](https://github.com/KyleAMathews/superagent-bluebird-promise)) to wrap superagent methods into bluebird promises.

Here's an example of a login API:

```
const request = require('superagent');
require('superagent-bluebird-promise');

const BASE_URL = 'http://localhost:8080';
const login = (credentials) => {
  return request
    .post(BASE_URL + '/login')
    .send(credentials)
    .promise();
 };
```

and then 

```
const LoginActions = Reflux.createActions({
  'login': {asyncResult: true}
});
LoginActions.login.listenAndPromise(login);
```

**Comment by bebraw** [comment]
By the way, if you are not opposed to trying out some other client, [axios](https://www.npmjs.com/package/axios) has worked really well. It's promise based by default.

**Comment by henri-hulski** [comment]
Axios looks really promising. 
Do you have a working example how to make a http request with axios and reflux? 
Do you need to switch the promise library with Reflux.setPromise?

**Comment by bebraw** [comment]
@henri-hulski Here's a quick example, https://gist.github.com/bebraw/2060641a7fae7264af2c . No need to switch Promise library as far as I understand.

**Comment by henri-hulski** [comment]
Makes it sense to use the promise or listenAndPromise methods here?

**Comment by bebraw** [comment]
@henri-hulski Not sure actually. It might be possible. Note that Axios `get` returns an object which contains data, status and headers as separate fields. I recall that was the reason why I ended up with the code I did. Of course these details can be abstracted out to make it fit Reflux APIs better.
