### ISSUE TITLE
call to wrong level action fails silently

### ISSUE THREAD

**Issue by mschipperheyn** [spoike/refluxjs#195]
var LoginActions = Reflux.createActions({
		"login": {
			children:[
				"loginSuccess",				// action after login is successful
				"loginFail"				// action after login fails		
			]
		}
	});

if I can LoginActions.loginSuccess accidently, it will fail without error or warning. I guess I would expect a missing action to raise an exception of some kind

**Comment by spoike** [comment]
Could you please describe the failure you're experiencing, @mschipperheyn? I'm not sure what you mean with accidently.
