### ISSUE TITLE
`Expected identifier` in IE8

### ISSUE THREAD

**Issue by Nevon** [spoike/refluxjs#202]
IE8 chokes on something in `PublisherMethods.js`, giving a `SCRIPT1010: expected identifier` error. Unfortunately, webpack puts the entire module in a single line string, so I don't know _where_ the problem is. I thought it would be a trailing comma, but as I don't see one, I would assume that some property is a reserved word in ie8.

**Comment by srph** [comment]
Probably ['catch'] as you referenced. But I'm sure this was pull requested before https://github.com/spoike/refluxjs/pull/187

**Comment by Nevon** [comment]
Oh, yeah I didn't see that pull request when I made mine. The usage of `catch` is indeed the only thing that's preventing Reflux from working in IE8. Once #187 is merged, this can be closed.

**Comment by spoike** [comment]
#187 is merged since it has a comment explaining the bracket notation. Closing this. Thanks for your contribution.
