### ISSUE TITLE
Can't test reflux actions and stores and jest

### ISSUE THREAD

**Issue by leocristofani** [spoike/refluxjs#210]
I just started using refluxjs and wrote some boilerplate code to start doing tdd with jest. The problem is that when I try to run my tests from the terminal with `npm test`, both the actions and the store commonjs modules are `undefined`.

#### AuthActions.js 
`actions/AuthActions.js`

```
var Reflux = require('reflux');

module.exports = Reflux.createActions([
    'register',
    'login',
    'updatePassword',
    'resetPassword'
]);
```

#### AuthStore.js
`stores/AuthStore.js`

```
var Reflux = require('reflux');
var AuthActions = require('../actions/AuthActions');

module.exports = Reflux.createStore({
    listenables: [AuthActions],

    onRegister: function(email) {},
    onLogin: function(credentials) {},
    onUpdatePassword: function(credentials) {},
    onResetPassword: function(email) {}
});
```

#### AuthStore-test.js
`stores/__tests__/AuthStore-test.js`

```
jest.dontMock('../AuthStore');
jest.dontMock('../../actions/AuthActions');

describe('Auth Store', function() {

    var AuthActions, AuthStore;

    beforeEach(function() {
        AuthActions = require('../../actions/AuthActions');
        AuthStore = require('../AuthStore');
    });

    it('should handle authentication actions', function() {

        console.log('AuthActions',AuthActions);
        console.log('AuthStore',AuthStore);

        AuthActions.register('banana@apple.com');
        expect(AuthStore.onRegister.mock.calls.length).toBe(1);

    });

});
```

#### Terminal output after running `npm test`

```
 FAIL  reflux/stores/__tests__/AuthStore-test.js (0.093s)
AuthActions undefined
AuthStore undefined
● Auth Store › it should handle authentication actions
  - TypeError: Cannot call method 'register' of undefined
        at Spec.<anonymous> (/*/*/proj/reflux/stores/__tests__/AuthStore-test.js:18:21)
        at jasmine.Block.execute (/*/*/proj/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:1065:17)
        at jasmine.Queue.next_ (/*/*/proj/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2098:31)
        at null._onTimeout (/*/*/proj/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2088:18)
        at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
1 test failed, 0 tests passed (1 total)
Run time: 0.355s
npm ERR! weird error 1
npm ERR! not ok code 0
```

**The weird thing here is are the lines that say**
`AuthActions undefined`
`AuthStore undefined`

When I export anything but **Reflux.createActions([])** and/or **Reflux.createStore({})**, I don't get undefined.

**Comment by kentor** [comment]
AuthStore depends on `reflux` and I bet that is getting mocked. `createStore` will return `undefined` under the mocked `reflux`.

**Comment by leocristofani** [comment]
That's a very good point Kentor, that I didn't think about. With that said, thanks very much for the comment. At least I know the issue know and have a direction to fix this.

**Comment by mlarcher** [comment]
@leocristofani, I'm facing the same issue. Would you mind sharing how you solved it ?

**Comment by srph** [comment]
@mlarcher 

You might want to start at `jest.dontMock('reflux');`

**Comment by mlarcher** [comment]
It appears dontMock is not enough, as reflux dependencies also need not to be mocked.
I fixed the issue by adding 
```
"unmockedModulePathPatterns": [
    "../node_modules/react",
    "../node_modules/reflux" // this is where reflux gets unmocked
  ]
```
to the jest config

**Comment by srph** [comment]
Ah, I see. Thanks. [`#JustGotSchooled`]() (jk :smile:)

**Comment by mlarcher** [comment]
Actually things are a bit more subtle than that, cf https://github.com/facebook/jest/issues/100#issuecomment-85137529
