### ISSUE TITLE
Chained dependent actions?

### ISSUE THREAD

**Issue by richardbutler** [spoike/refluxjs#212]
I have a scenario where I have two independent actions (`FindNearestCourses`, `FindNearestUsers`) that both have the same dependency action (Geolocate). I need to call the `Geolocate` action before each of them can send their relevant ajax request. The non-Flux flow would be something like this:

```js
function findNearestUsers () {
  geolocate().then(function (location) {
    // Cache location somewhere
    request('/users/nearest').params(location).then(function (users) {
      // Do something with users
    });
  });
}
```

But in Reflux world, I simply call `FindNearestUsers()`. I have a `ClientSessionStore` that listens to `Geolocate.completed` and stores the geolocation data, but how do I make a call to `FindNearestUsers()` trigger the `Geolocate` action, and then consume the result of it? From what I can see, preEmit wouldn't cut it here, and wouldn't scale for chains of more than two actions.

Have I missed something obvious? :)

**Comment by spoike** [comment]
I think it is totally valid to use a promise inside stores so your geolocation doesn't need to be an action. "Finding" is not really a data flow, it is more an end to the means. So what the application is doing is an update. It updates courses and users data when the location has been changed.

So you may have a geolocate function that returns a promise that can be used by a `CoursesStore` and a `UsersStore`. Sort of like this:

```javascript
var Update = Reflux.createActions(["Location"]);

Update.Location.preEmit(function() {
    return geolocate();
});

var UsersStore = Reflux.createStore({
  listenables: [Update],
  onLocation: function(updateLocation) {
    updateLocation.then(function() { /* ... */ });
  }
});

var CoursesStore = Reflux.createStore({
  listenables: [Update],
  onLocation: function(updatedLocation) { /* ... */ }
});
```

Hope this helps!

**Comment by richardbutler** [comment]
Thanks, that makes sense. However, does `preEmit()` to accept a promise? It didn't work for me.

I actually since discovered `action.triggerPromise()`, which helps with chaining actions:

```js
var geolocate = reflux.createAction({ asyncResult: true });
geolocate.listen(function () {
    navigator.geolocation.getCurrentPosition(this.completed, this.failed);
});

var findNearestUsers = reflux.createAction({ asyncResult: true });
findNearestUsers.listen(function () {
    geolocate.triggerPromise().then(function (location) {
        this.promise(request('/blah').params(location));
    }.bind(this));
});
```

This seems to work nicely. With a bit of sugar, it would be quite straightforward to build in a chaining helper to `createAction()`, something like this:

```js
var geolocate = reflux.createAction({ asyncResult: true });
geolocate.listen(function () {
    navigator.geolocation.getCurrentPosition(this.completed, this.failed);
});

var findNearestUsers = reflux.createAction({
    asyncResult: true,
    dependencies: [geolocate]
});
findNearestUsers.listen(function (location) {
    this.promise(request('/blah').params(location));
});
```

**Comment by spoike** [comment]
:ok_hand: cool. Nice use of `triggerPromise()` and chaining helper.

I thought preEmit would be able to pass on anything... maybe it's a bug?
