### ISSUE TITLE
Jest testing: listeners not working

### ISSUE THREAD

**Issue by nathanharper** [spoike/refluxjs#218]
I can't seem to get action listeners to work at all when testing with Jest. I made this really basic example:

```
'use strict';

jest.autoMockOff();

describe('Test', function () {
  it('Tests listenables', function () {
    var Reflux = require('../node_modules/reflux/index');

    var actions = Reflux.createActions([
      'action1',
    ]);

    var mockFn = jest.genMockFn();

    var store = Reflux.createStore({
      listenables: actions,
      onAction1: function () {
        mockFn();
      }
    });

    actions.action1('Hello World');
    expect(mockFn).toBeCalled();
  });
});
```

And it always gives me

```
Expected Function to be called.
```

Am I doing something wrong?

**Comment by gothy** [comment]
Same problems here :(

**Comment by nathanharper** [comment]
yeah... for now I've been getting around it by doing stuff like

```
var someAction = jest.genMockFn().mockImpl(myStore.onSomeAction);
```

...but it would be nice to have a way to test that action listeners are all actually hooked up correctly.

**Comment by nathanharper** [comment]
I figured it out! You just have to fast forward all the timers before any `expect` calls. For my example, it was as easy as adding this:

```
jest.runAllTimers();
```
