### ISSUE TITLE
Reusable components: How to hook up stores?

### ISSUE THREAD

**Issue by thiloplanz** [spoike/refluxjs#220]
I have a question about how to hook up reusable components with the stores they want to listen to. 
All the examples in the documentation have React.createClass definitions that directly refer to the store as a global variable. That way, all instances of this component will share the same store.

Shouldn't this be configurable via component properties instead, so that the user / parent component can decide which store to use? Something like `this.props.stores` ?

A very similar question is #193. There, it is suggested to use a factory to create classes, with the store being injected. That way, you'd have multiple copies of the some component class definition, which seems like an odd thing to do.

**Comment by spoike** [comment]
My approach has usually been to let the top most level components (usually a page component or route handlers) to use stores and trinkle (or inject) that data down through `props`. 

If you're just passing data around isolated to one component or inside a parent component, then you should be doing it as usual in React, so there is no need for Flux there.

**Comment by abritinthebay** [comment]
Spoike has the right approach.

thiloplanz - you need to read the Flux pages again (reflux does a terrible job at documentation of Flux patterns in it's readme). What spoike is referring to is called a Controller-View in the Flux terms.

Basically it takes the data from a store and sends it *as just data* down the chain of its children.

Components should *just be data driven* for the most part.

**Comment by thiloplanz** [comment]
> let the top most level components use stores and trinkle (or inject) that data down through props.

Yeah, that's what I ended up doing.

However, there are some big inconveniences with this:

1) A lot of boiler-plate to hand down the properties across the component tree. 

2) No encapsulation. A parent component needs to know a lot about its child components (and their child components) in order to be able to pass the relevant data down. 

3) Unclear distinction between *UI state* and *application data*. Now I have everything as properties, including "static" component configuration, "data-derived" component configuration and "pure UI state" (such as uncommitted user input or validation messages). I'd really like to keep the latter encapsulated in the components themselves. It seems I should be using `state` instead or `props` here.

**Comment by abritinthebay** [comment]
> 1) A lot of boiler-plate to hand down the properties across the component tree.

Shouldn't be too much. It's just data. If you're treating it as anything more than data I can see how this could be a problem but at the end of the day the Parent needs to know what to assign props to for it's children.

You can listen to Stores directly and filter the data but the problem then comes in as - what if you re-render further up the chain? If the parent doesn't know these things you'll lose the data you had in the child components. Never change props and never store application state in a Component. etc etc

> 2) No encapsulation. A parent component needs to know a lot about its child components (and their child components) in order to be able to pass the relevant data down.

All it needs to know is "I need to pass it this data" that's it. Which it obviously needs to know to be able to render the component reliably given the same input data. Which is core to React tbh.

> 3) Unclear distinction between UI state and application data.

This really makes me feel you're doing something very wrong here. UI state is anything that is going in in the individual component. App state is for the Store. Never the twain shall meet.

One is kept in the components state field, the other is in the data store. How can these be any *more* distinct? The component gets the *data* it needs to render itself, but it doesn't care about the app state... just whatever data it is passed.

**Comment by ivan-kleshnin** [comment]
@abritinthebay 

> The component gets the data it needs to render itself, but it doesn't care about the app state... just whatever data it is passed.

You're forgetting that components render both app and UI state... Stores render nothing.
So they, of course, "shall meet" at render time...

**Comment by abritinthebay** [comment]
> components render both app and UI state... 

... are you using some kind of strange version of "app state"? Because sure - the UI is a *reflection* of app state, but only in so much that it uses what data from the app state that is required.

That's data - not the pure state being passed around.

**Comment by abritinthebay** [comment]
> So you either don't quite understand what you're proposing or you have some cool sync-only architecture of Stores in mind. Please share.

If you think this needs to be sync-only - well I have news for you: I'm doing it async right now as we speak. It is you that doesn't understand what you're proposing. In fact it seems you don't understand anything I said.

I mean the following is just... bad app design:

> If component pulls data from store at render time – you'll get async calls from render very soon.
And async calls from render mean render is no longer pure.

It's like... you don't know how to structure your app to get the data outside of the render call. That's React 101 and not even that hard. This, in fact, is where the whole hydrate/dehydrate system would be useful.

Store is hydrated with data at load -> Store triggers self that it's updated -> component gets data.
This is the same as:
Component calls Action for loading Data -> Store updates data -> Store triggers -> component loads data.

There is nothing in this that is hard to do with the system I described. I should know: I'm doing it now.

**Comment by ivan-kleshnin** [comment]
@abritinthebay, a lot of personal blames and random strange statements. 
Don't see a point to continue.

**Comment by abritinthebay** [comment]
You didn't have a point to begin with Ivan. Your lack of ability is not my problem.

**Comment by andrest** [comment]
@thiloplanz this is a question I've been pondering about as well. Props seem the right way to go about this till you find that you're passing something to child 7 components deep. As you build up to it, it's annoying but you can deal with it. However, later, when you figure you have to access the state of the child at the top, or bring in a bunch of more props, it gets blooooody annoying. Passing everything down {...this.props} became the commonly used short-cut but that didn't feel right for tiny components.

Currently, for the larger widgets, the children interface with the stores directly. Not ideal due to tight coupling, but keeps me sane.

I'm thinking of moving component state over to a store by creating a store for every view. This would be creating somewhat more boilerplate but would simplify data flows. Ideas appreciated.

**Comment by abritinthebay** [comment]
> However, later, when you figure you have to access the state of the child at the top

Do you mean from a child Component? because that sounds like it should be dealt with indirectly (events, actions in flux, etc etc) rather than directly.

> Currently, for the larger widgets, the children interface with the stores directly. Not ideal due to tight coupling, but keeps me sane.

I'd be careful with that - FB considers it something of an anti-pattern (but occasionally useful). 

> I'm thinking of moving component state over to a store by creating a store for every view.

That's *explicitly* not what Stores are for. That's treating them as basically just Models. Perhaps trigger updates with `.trigger("someEventName", data)`? Then the component can listen specifically for data it knows it needs via the event name. Might not be perfect but it's certainly better than duplicating Stores like that.
