### ISSUE TITLE
action logs

### ISSUE THREAD

**Issue by geddski** [spoike/refluxjs#224]
I'm playing with reflux, really like it so far. A friend explained to me that the main benefit of Flux's dispatcher is to prevent actions from firing actions from firing actions (remember backbone?). With reflux it's possible to have a store listen to an action and trigger a new action, which in turn triggers other actions which could easily become intractable. I understand it's probably not possible to queue up the actions without a dispatcher, but would it be possible to at least (optionally) enable console logging on each action to know which actions are being fired?

**Comment by spoike** [comment]
At the moment to log all actions you have to iterate over all actions in `Reflux.__keep.createdActions` and register a simple listener on them to console log the arguments. Something like this:

```javascript
var _ = require("lodash"),
    Reflux = require("reflux");

function consoleListen(action) {
    return function() {
        console.log(action.name, arguments);
    };
}

_.each(Reflux.__keep.createdActions, function(action) {
    action.listen(consoleListen(action));
});
```

It is admittedly a bit hacky, but it is to my knowledge the only way to do it at the moment without dealing with it inside the application.

**Comment by fskreuz** [comment]
Digging this up, this would be a great tool for debugging the application. Read up on this slide, https://speakerdeck.com/jmorrell/jsconf-uy-flux-those-who-forget-the-past-dot-dot-dot, slide 58. One can easily replicate the application state if the sequence of actions were logged, and optionally, a serialized version of the arguments passed in.

```
Reflux.debug= true; // Enables tracking
Reflux.trace(); // logs everything called since the application was loaded
Reflux.trace({
  displayArgs: true
}); // Logs actions as well as the serialized data passed through.
```
