### ISSUE TITLE
ES6 class support

### ISSUE THREAD

**Issue by torarnek** [spoike/refluxjs#225]
It would have been fantastic if I could do:

class MyStore extends Reflux.Store {
  init(){
 ...
  }
}

This would allow editors/jshint/flow to more easily do code checks, like checking method names, than what is possible with a dynamic object that Reflux.createClass gives. 

Any chance for this in the near future? :)

**Comment by spoike** [comment]
Maybe. We're using mixins to build up the stores, actions and joins.

I'm aware that React has API for ES6 classes, [however by using that you're also opting out of mixins](http://facebook.github.io/react/blog/#mixins).

To be honest I'm not a big supporter of classes in Javascript since mixins (or in other languages traits/roles) has been proven to be more flexible in for me personally in my daily dev work. So I won't be working on it however I'd accept PR if such would come up.

**Comment by Turbo87** [comment]
there is a difference compared to the react components because when you call `Reflux.createStore()` an actual instance is generated, but when you call `React.createClass()` it is more like a class definition, that is only instantiated when calling the `React.render()` method. Due to that I'm not sure if replacing the `createStore()` call with ES6 classes is actually possible.

**Comment by zbyte64** [comment]
Not sure if I follow the hangup over returning a class. You can define a store and instantiate it:

```
class PageStore extends Reflux.Store {
  constructor(myInitialState) {
    this.state = myInitialState || Immutable.Map()
    this.listen(AddPageSuccess, this.addPageSuccess)
  }
  setState(delta) {
    this.state = this.state.merge(delta)
    this.trigger(this.state)
  }
  addPageSuccess(pageResult) {
    this.setState({page_id: pageResult})
  }
}

var PageState = PageStore();

var PageListing = React.createClass({
  componentDidMount: function() {
    PageState.listen(this.onPageState)
  }
})
```

So I guess the cost is one extra line of code to use an es6 class.

**Comment by bengotow** [comment]
Wait—I'm not sure I follow. Is your syntax above an existing feature? `Reflux.Store` doesn't seem to be defined in https://github.com/spoike/refluxjs/blob/master/src/index.js, and my test case fails:

```
class TestStore extends Reflux.Store
  constructor: ->

TestInstance = TestStore()
```

(Error:Cannot read property 'prototype' of undefined)

**Comment by mvcninja** [comment]
You can easily get the `class` from the instance, as an ES6 class is just a prototype- 
```javascript
Reflux.Store = Reflux.createStore().prototype;

class MyStore extends Reflux.Store {
  constructor() ->
}

let instance = new MyStore();

**Comment by LongLiveCHIEF** [comment]
I am also not in favor of classes, at least in the way they're implemented via es6.  Javascript, as a functional language, has a lexical scoping/"inheritance" model that the es6 classes implementation can wreak havoc on in a moderate to large application environment.

Classes are great for peaking the interest of Ruby/PHP/Java developers, and helping them to adopt javascript, but they aren't a prototypal construct, and really don't deserve a place in this language.

There I said it. Classes are bad javascript.

That being said... the beauty of javascript is such that you can prototypically extend a library however you wish after requiring it in, and can use classes in your own code. If you wish, regardless of the authors/maintainers opinions about them. #javascriptFTW

I am working on some es6 refactoring of reflux at the moment, so keep an eye out for that.

Personally, I'd vote against any PR that uses classes in core reflux.

**Comment by blainekasten** [comment]
So, real talk here, if Reflux doesn't adopt es6 classes, this library may fall to the wayside as React is very much moving towards ES6 classes, and it's adoption is growing. You may want to seriously consider this. You could do the React approach and support both of them. You should also look into using context, as that's the new method to do 'mixin-like' things with React ES6 components.

**Comment by oriSomething** [comment]
you can also use `ES7 decoratore`s instead of `mixin`s. this is what i do

**Comment by DaZzz** [comment]
Agree with @blainekasten.

@oriSomething can you provide an example of usage? Can I use react ES6 classes with reflux mixins somehow?  :full_moon_with_face:

**Comment by blainekasten** [comment]
@oriSomething using es7 decorators is pretty bold as it's not yet standardized (stage 1). 

@DaZzz You can use reflux with es6 react classes like so:

```js
import store from 'MyRefluxStore';

class Comp extends React.Component {
  componentDidMount() {
    this.unsubscribe = store.listen( () => this.setState({ data: store.getData() }) );
  }

  componentWillUnmount() {
    this.unsubscribe();
  }
}
```

}

**Comment by oriSomething** [comment]
@DaZzz hey, i've used implantation similar to [this](https://gist.github.com/oriSomething/36492428024fb284bcdd).

@blainekasten it's true decorators are not standardized, but also react is still far from 1.0, and every version there are new breaking changes and pretty much, most of the JS technologies we use today. and still decorators might still be in the beginning, but there is very little todo to get similar effect with today JS, like:
```js
class MyComponent extend React.Component {
 ...
}

export default connectStore(MyComponent, someRefluxStore);
```

**Comment by rymohr** [comment]
Looks like @AlexJozwicki is already working on an es6-based port: https://github.com/AlexJozwicki/airflux

I'm still undecided. I like mixins but I agree with @blainekasten, the react team is moving full steam towards classes.  Here's a great post on the topic: https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750

**Comment by alex94puchades** [comment]
BabelJS, one of the transpilers with better support for JSX, already has support for decorators (by means of `{ optional: ['es7.decorators'] }`). Is the goal to not have anything ES6 related in Reflux core? Or only to maintain backward-compatibility? Cause implementing Reflux.createStore on top of classes and (maybe) decorators would be easy.

**Comment by udsndesign** [comment]
@rymohr, Hi my friend, i'm working on  @AlexJozwicki Airflux, but i cant make work together react and airflux, the state always come undefined, but if i use airflux  only with js it works like a charm. 

Do you have any examples of react  + airflux working together? 
In documentation of airflux dosent have a full exemple, only fragments of ramdom codes.

It would be helpful, thank you!

**Comment by udsndesign** [comment]
@AlexJozwicki Do you have any examples of react + airflux working together?

**Comment by grimen** [comment]
If ES6 classes is not considered for the project because of ideolistic reasons, I guess the community will just use a fork (pure or shim). Don't see why this is even a discussion, pretty much everyone embracing ES6 classes now that is part of the standard and hardly is a cost.

**Comment by H3Chief** [comment]
@grimen read the writing on the wall.  This project is dead.

**Comment by snario** [comment]
:(

**Comment by danielstorch** [comment]
So... i should use flux from FB instead? Im new to all this and have problems using mixins since my project is build up on ECMAScript 2015. 
Cant figure out how to use `mixins: [Reflux.connect(statusStore,"currentStatus")] ` while using `export default class Navigation extends React.Component {}`

**Comment by spoike** [comment]
This project isn't really dead, check #436 for details on why development has been slow lately.

Regarding class support, there are a bunch of reflux plugins on npm that can be used in tandem. E.g. [`reflux-provides-store`](https://www.npmjs.com/package/reflux-provides-store)

**Comment by blainekasten** [comment]
@danielstorch I would sugest [Redux](https://github.com/rackt/redux). The creator of that recently got hired by FB to work on React core if that is an indicator of anything.

**Comment by Flourad** [comment]
@blainekasten I have a question.
```
class Comp extends React.Component {
  componentDidMount() {
    this.unsubscribe = store.listen( () => this.setState({ data: store.getData() }) );
  }

  componentWillUnmount() {
    this.unsubscribe();
  }
}
```
The method above is helpful for me, but when i need to listen two different stores in the Comp component, i how use the unsubscribe to remove two listener??

**Comment by Flourad** [comment]
@jamesmarrs Thank you for your answer, it inspires me~

**Comment by BryanGrezeszak** [comment]
This page gets a lot of google hits, so I think this is a good place to note that Reflux is now implementing a version of `Reflux.Store` for ES6 extension (as well as `Reflux.Component`). See info here: https://github.com/reflux/refluxjs#react-es6-usage

**Comment by santhosh77h** [comment]
@Flourad  saved me from one more day of analyzing since this issue is related to bind I was trying to put arrow function so I checked it that way it was not working I have never thought it's because of reflux.....
