### ISSUE TITLE
Action.triggerPromise is probaby not what you expect

### ISSUE THREAD

**Issue by robcolburn** [spoike/refluxjs#228]
The idea of `triggerPromise` is that you can "trigger" and action, and collect the promise of that action completion and result, and therefor it's result.  But, here's the rub, Actions are EVENTS.  So, you are returned a promise resolved when any trigger of the action is completed.  I've probably lost you, but let's see this play-out.

Let's take a simple Reflux component layout…

```jsx
RefreshTransactions = {}
RefreshTransactions.load = Reflux.createAction({async: true})
RefreshTransactions.load.listenPromise(params => api.promise(params))

TransactionStore = Reflux.createStore({
  listenables: [RefreshTransactions],
  data: [],
  getInitalState(){
    return this.data
  },
  onLoadCompleted(data){
    this.trigger(this.data = data)
  }
  onLoadFailed(){
    this.trigger(this.data = [])
  }
})

TransactionView = React.createClass({
  mixins: [Reflux.connect(TransactionStore, 'transactions')],
  render(){
    return <ul>{this.state.transactions.map(t =>
      <li>{t.name} {t.amount} {t.date}</li>
    }</ul>
  }
})

app.use(function(req, res, next) {
  RefreshTransactions
    .triggerPromise(req.query.accountId)
    .then(function(data){
      TransactionStore.data = data
      res.send(React.renderToString(<TransactionView accountId={req.query.accountId} />))
    })
})
```

Query-strings are clearly a bad idea, esp with accounts, but I'm trying to show something trivial. Here's the problem on the server, let's say three requests come in around the same time.
* /transactions?accountId=1
* /transactions?accountId=2
* /transactions?accountId=3

So, your isomorphic app runs out to grab that data from the api.  When the first response comes in from the API… the action fulfills *all* promises.  Which means you'll end up rendering the same result for all three requests.

Now, I'm not dealing with accounts and transactions, but I do want a promise of when *my* trigger is done.  You can solve this simple example in a dozen different ways, but they are likely all stepping out using Reflux.  Is there a way to do this in Reflux?

**Comment by madjam002** [comment]
+1
I was wondering how reflux handles this but yeah it turns out it doesn't.

Instead of the proposed monkey patching on #229, can we not just have an alternative to `listen` (such as `usePromise`) which returns a promise, and then when you call `triggerPromise`, it checks to see if `usePromise` has been defined, then calls it if it has and uses the promise returned by that instead of creating its own.

```coffee
actions = Reflux.createActions(
  'get': { asyncResult: yes }
)

actions.get.usePromise = (params, here) ->
  return someActionWhichReturnsAPromise(params, here)
```

I'll fork reflux later and give this a go.

**Comment by madjam002** [comment]
Actually, I'm not too sure about my idea now.
You can just call your action normally and it will return a promise, but it forces it to be a synchronous action and the callback for the promise is called before the completed child action, meaning your stores won't have updated when the promise is resolved.

Anyway, I've put the code here anyway madjam002/refluxjs@ac808f6ee9db2e228b4be614e7b754fda4dc5063

**Comment by robcolburn** [comment]
@madjam002,
Not sure how that quite helps, but let's boil the problem down to an even simpler example.

https://gist.github.com/robcolburn/21c206a94d881a897b6e

The problem is the loss of context.  `triggerPromise` triggers the ActionEvent and hands back a promise, but it is not able to guarantee that the promise it gives you relates to the trigger you just performed.  So, your code has the exact same bug as:

https://gist.github.com/robcolburn/da3f1d8f6fcb0c05b625

But, what you really-really want, is to get the pancake you ordered.  Not a xerox copy of the last pancake ordered.  That's what you were *promised* after all.  I've built out a Reflux/React "pre-loader" for the server-side app, and applying such a patch was critical.  Though I realize the I submitted in the PR was incomplete (because I was copy-pasting code ;) ).  I'll submit a better patch.

**Comment by ericclemmons** [comment]
Ah, crap.  I was afraid of that.

In my case, I have an instance of the store per-request, so actions were only called once.

This is indeed a problem in cases like you've shown.

The promises can resolve in any order, too, so somehow the solution has to maintain contexts between the action and the success/failure events...

(I need to think about this a bit more)

**Comment by robcolburn** [comment]
Before writing the pre-loader, I debated per-request stores, or
re-instantiationpretty stores. But, for better or worse, decided that I
wanted to "lean-in" toward a client-side app that happens to run on the
server and that should mean leaning into React Router and Reflux.

I spent a lot of time thinking about how to make triggerPromise generic
enough to handle the non-promised case: listen + completed & failed.
Ultimately, I concluded it was impossible, or at least impossible without
painfully refactoring Reflux's async Actions in a non-backward-comparable
way.

Async Actions are designed to listen to completed and failed "child
actions" aka "child events" which have context of their parent Action, but
do not have context of their "parent trigger".  You could fire
`MakePancakes.completed(10)` from an entirely unrelated block of code.

It should probably be that "completed" and "failed" are not exactly Actions
nor Events. Instead, async Actions should likely always have a new embedded
Promise for each time they are triggered, with a
resolve/reject/(progress?) mechanism rather than event-like mechanism.
Because:
* Do we want an async Action to just compete without a trigger?
* Do we want an async Action to complete/fail more than once for a given
Action trigger? You may side-track and think of a few cases, but you're
probably actually wanting a "progress".

What we should probably do is rewrite async Actions to be Promise-based
(well, probably Deferred-based).  Keeping that `action.completed` as
listenable, but only fires from a corresponding trigger.  This is tricky,
and involves that non-backward compatible change.  We need to pass a
context to our listeners which we could do via an arguments or `this`
binding.

```js
EatPancakes.listen(function(count){
  EatPancakes.competed(count+1);
});
EatPancakes(1);
```

Becomes

```js
EatPancakes.listen(function(count){
  this.competed(count+1);
});
EatPancakes(1);
```

Either way, that's breaking existing code. So, maybe we continue to support
`action.completed` being called statically, and just lookup the last
promise made, and while we're at it throw a deprecation warning to the
console.

One un-fun note, is that `listen` currently allows you to pass in the
`bindContext` as a bit of sugar instead of the more common way of doing
that (forcing the caller to call `Function.bind` themselves. So, we would
need to either deprecate that sugar, or change the arguments pattern.

--
Rob Colburn

On Sat, Feb 14, 2015 at 6:34 AM, Eric Clemmons <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Ah, crap. I was afraid of that.
>
> In my case, I have an instance of the store per-request, so actions were
> only called once.
>
> This is indeed a problem in cases like you've shown.
>
> The promises can resolve in any order, too, so somehow the solution has to
> maintain contexts between the action and the success/failure events...
>
> (I need to think about this a bit more)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spoike/refluxjs/issues/228#issuecomment-74377311>.
>



-- 
--
Rob Colburn

**Comment by robcolburn** [comment]
My approach to avoid massive refactor, was to just only allow a genuine
promise if the implementor is being "good", and using `listenAndPromise`.
Perhaps we show throw a console warning when they are not being "good"
though?

-- 
--
Rob Colburn
