### ISSUE TITLE
Flux Best Practices: Storing global data in the Store?

### ISSUE THREAD

**Issue by sahat** [spoike/refluxjs#233]
I am still relatively new to the Flux architecture so this might be a question with an obvious answer.

I have 3 primary components: **App**, **DirectionsOverlay** and **Maps**.
```html
<div id='container'>
      <DirectionsOverlay />
      <Maps />
</div>
```
![screenshot 2015-02-08 17 48 52](https://cloud.githubusercontent.com/assets/544954/6099951/c4dfeab6-afba-11e4-8cba-5415cc09eb7e.png)

In the example above, **Directions** component invokes an action `getDirections`, which it does successfully, however to display them I need an instance of the map, which is stored in the `state` of the **Maps** component.

As far as Flux goes is it okay to store the global `var map = Object` instance inside a store as a plain JS variable and then have a getter/setter action to get that map instance across multiple components in my app, including **Maps** component itself.

Thanks.

Also, great library @spoike, much less boilerplate than Facebook's Flux implementation.

**Comment by spoike** [comment]
> As far as Flux goes is it okay to store the global var map = Object instance inside a store as a plain JS variable and then have a getter/setter action to get that map instance across multiple components in my app, including Maps component itself?

Sure, if that works for you then it is okay. Stores are supposed to hold all the data that the components need between each other.

**Comment by sahat** [comment]
Thanks!
