### ISSUE TITLE
Mixin breaks server side rendering

### ISSUE THREAD

**Issue by kjs3** [spoike/refluxjs#250]
I'm integrating react with reflux into a rails app using react-rails.

Subscribing to a store in componentDidMount and unsubscribing in componentWillUnmount is working but then I have to manually call a store method to get initial state.

If I try to connect to a store with any of the mixin methods I get an error because setTimeout isn't available server side. JS is being processed server side by therubyracer gem (V8 wrapped in ruby).

Is this caused by the nextTick function being hoisted and could it be deferred?

**Comment by spoike** [comment]
You can [set Reflux to use another nextTick function](https://github.com/spoike/refluxjs#switching-nexttick). Like this:

```javascript
Reflux.nextTick(function(cb) {
  cb(); // immediate invocation
});
```

**Comment by kjs3** [comment]
Hmm, now I'm getting "document is not defined".
Are other people successfully rendering components that use reflux mixins server side?

**Comment by kjs3** [comment]
Nevermind, "document" was unrelated to reflux. 
I'm still getting the setTimeout error even after changing the source nextTick to execute immediately.
The only setTimeout left is in the promise blob from Kyle Simpson (line 213).
I'm not sure what to do about that one.

**Comment by nambrot** [comment]
I'm also trying to get reflux to work server side in Rails, would love to hear if you have made it work

**Comment by jslatts** [comment]
I was having the same issue (server side rendering using ClearScript V8 via Reactjs.NET). In my case, the issue was caused by browserify crawling down the dependency tree and setting up a require statement for the native-promise-only library that reflux uses. 

Since I don't actually need to execute reflux code server side, I was able to get things working by using browserify's *ignore* method which keeps the require statement but replaces the target module with a NOP function:

```
var b = browserify({
  extensions: ['.jsx', '.js'],
  transform: [reactify]
  })
  .ignore('native-promise-only')
  .....
```

Hope this helps.

**Comment by matekb** [comment]
I'm having the same problem with setTimeout. Have you had any progress with this?

The following is my stack trace:

```
Encountered error "ReferenceError: setTimeout is not defined" when prerendering ProductionInfoBox with {}
(execjs):21587:15187
(execjs):21587:13142
Object.<anonymous> ((execjs):21587:13265)
Object./Users/mattias/git/ecp/node_modules/Reflux/node_modules/native-promise-only/npo.js ((execjs):21587:16566)
a ((execjs):21586:262)
(execjs):21586:313
Object./Users/mattias/git/ecp/node_modules/Reflux/src/utils.js.eventemitter3 ((execjs):21587:32718)
a ((execjs):21586:262)
(execjs):21586:313
Object./Users/mattias/git/ecp/node_modules/Reflux/src/ListenerMethods.js../joins ((execjs):21587:17113)
```

**Comment by spoike** [comment]
Related to #302

**Comment by kjs3** [comment]
@nambrot Not just related to this, but this coupled with other server side js friction with rails has lead us to split our monolithic app into a rails api and node serving the frontend. This obviously has it's own challenges but our project was early enough that I felt we should bite the bullet rather than continue dealing with js-as-a-second-class-citizen in rails.

**Comment by rearadmiral** [comment]
Was this closed as Won't Fix?

In my server-side code, I have this hack:

```javascript
global.setTimeout = null;
```

Which allows me to use reflux using react-rails and server-side rendering (what they call "prerendering")

It would be ideal if the check used by reflux was more tolerant to this object not being defined.

**Comment by rearadmiral** [comment]
With version 0.2.8, if I add both of these workarounds:

```javascript
global.setTimeout = null;
(function() {
  var Reflux = require("reflux");
  Reflux.nextTick(function(cb) {
    cb(); // immediate invocation
  });
})();
```

Everything works fine. With just one of them, I get an error about setTimeout not being defined.
