### ISSUE TITLE
How to structure an app

### ISSUE THREAD

**Issue by paglias** [spoike/refluxjs#251]
Hi,

I'm quite new to the ReactJS world coming from a AngularJS background and while I really appreciate React itself I'm having a few problems understanding how Flux is supposed to work.

Actually to better learn React and Reflux I've decided to build a simple money tracking app.

The structure is the following:

1. There is a list of Accounts
2. There is a list of Transactions with each Transaction that reference an account through `transaction.accountId`
3. There's a currently selected account so that the transactions inside that account should be shown
4. When a transaction is updated/moved/deleted it's account balance should be updated

I've built it with React+AmpersandJS (similar to Backbone) so using Models, Collections and events but I'm having serious problems on how to do it with Reflux.

In particular:
1. Should any logic be put in Actions or they are just a way to dispatch events?
2. Stores are allowed to have methods called directly (like Store.findOne()) or they should just respond to actions and trigger new data?
3. Should I keep a store for each item on a list? With Stores able to trigger just a type of events and not multiple ones sometimes I feel like recalculating all the logic in order to apply just a simple change is a big waste and that instead I should update just the affected child component

If you could give me an example it would be wonderful, thanks!

**Comment by dmwyatt** [comment]
1.  Business logic should be in the stores.
2.  You can call methods on stores as this is where your business logic should live.
3.  Depends on if you have lots of logic for an item on a list.  Don't worry about recalculating unless you've got an actual performance problem.
