### ISSUE TITLE
open EventEmitter and Promise

### ISSUE THREAD

**Issue by maxguzenski** [spoike/refluxjs#253]
Hi, I use Reflux from dist/reflux.js and wordering if I can use Promise and EventEmitter from Reflux... something like "var Promise = Reflux.Promise;".

if not, can you open it to use?

**Comment by spoike** [comment]
Sure, would be nice to expose all the internal stuff in case you want to use it.

Not sure about exposing Promise since Reflux should be using the native one if possible.
