### ISSUE TITLE
Am I doing this async stuff right?

### ISSUE THREAD

**Issue by alexciarlillo** [spoike/refluxjs#255]
I am trying to learn the *proper* way to make async API calls and hook them up to stores. The following works, but I am trying to make sure I am on the right track before I write my complete implementation. I think the example here is pretty straightforward. Pulling a list of posts from a WordPress site using a provided API module.

###### PostActions.js
```
/* jslint node: true */
'use strict';
var Reflux = require('reflux');

var PostActions = Reflux.createActions({
	"loadPosts": {asyncResult: true}
});

module.exports = PostActions;
```

###### PostStore.js
```
'use strict';
var Reflux           = require('reflux');
var PostActions  = require('../actions/PostActions.js');
var WP               = require( 'wordpress-rest-api' );

var wp                = new WP({endpoint: WP_API_Settings.root});

var PostStore = Reflux.createStore({
    listenables: [PostActions],
    data: [],
    onLoadPosts: function() {
    	wp.posts()
    		.then(function(data) {
    			PostActions.loadPosts.completed(data);
    		})
    		.catch(function(err) {
    			PostActions.loadPosts.failed(err);
    		});
    },
    onLoadPostsCompleted: function(data) {
		this.trigger(this.data = data);
    },
    onLoadPostsFailed: function(err) {
    	this.trigger(this.data = []);
    },
    getInitialState: function() {
    	return this.data;
    }
});

module.exports = PostStore;
```

###### App.jsx (top level component)
```
'use strict';
var React                  = require('react');
var Reflux		  = require('reflux');
var PostList               = require('./PostList.jsx');
var PostStore	          = require('../stores/PostStore.js');

// Renders the full application
var App = React.createClass({
    mixins: [Reflux.connect(PostStore,"posts")],
    render: function() {
        return (
        	<div id="reactwp">
	        		<div className="row">
	        			<div className="col-sm-8 col-sm-offset-2">
	            			<PostList posts={this.state.posts} />
	            		</div>
	            	</div>
	            </div>
	        </div>
        );
    }
});

module.exports = App;
```

###### PostList.jsx (component that displays from the store)
```
var _ = require('underscore');
var React = require('react/addons');
var ReactRouter = require('react-router');

var PostActions = require('../actions/PostActions.js');
var SinglePost = require('./SinglePost.jsx');

var PostList = React.createClass({
    propTypes: {
        posts: React.PropTypes.arrayOf(React.PropTypes.object).isRequired,
    },
    componentWillMount: function() {
        PostActions.loadPosts();
    },
    createEntry: function(post) {
        return (
            <SinglePost key={post.ID} post={post} />
        );
    },
    render: function() {            
        return (
            <div>{ this.props.posts.map(this.createEntry) }</div>
        );
    }
});

module.exports = PostList;
```

Is componentWillMount a good place to begin the async call? Am I triggering the completed and failed events of the async action correctly from within the store? I am still trying to wrap my head around this and find the documentation on the async stuff a little confusing.

**Comment by jankuca** [comment]
You should call the `PostActions.loadPosts` action from somewhere else. I'd recommend to do this from where you are mounting the `App` component.

The `completed`/`failed` trigger calls are correctly placed I believe.

**Comment by alexciarlillo** [comment]
Would it be okay to move the PostStore completely to PostList.jsx and connect it there instead of in App.jsx? PostList would then access this.state.posts instead of this.props.posts (I think)... and I could call PostActions.loadPosts on getInitialState? 

I would think it would be preferable to keep the stores connected only in the components they are used by. I'm not sure why in the code above I connected the PostStore to the App... I was just experimenting with a lot of different things.

**Comment by srph** [comment]
It's okay if PostList.jsx is a ```Controller-View```.

By the way, (noob here) in case the ajax call fails, how do you plan to handle it?

**Comment by jankuca** [comment]
@alexciarlillo I think you are not supposed to call actions in `getInitialState()` or `componentDidMount()`. Actions should be called based on input or explicitly at the time of mounting from above the component.

I understand why you'd like to call it in `getInitialState()` but stop for a sec and think about it. What if you had two instances of this component next to each other. Each would be initialized with a `getInitialState()` call upon mount and you would end up with two `loadPost()` triggers, thus two requests for posts. You really don't want to create your architecture around such a mistake.

This is how I'd recommend you do it:

```javascript
var app = App();
react.render(app, domNode);
PostActions.loadPosts();
```

**Comment by alexciarlillo** [comment]
@srph I would probably just display an error state on the component, maybe trigger a retry on 1 second timer from setTimeout() depending on what the component is, or put in a UI button to retry on error.

@jankuca that makes perfect sense. I had a feeling there were reasons that I was not foreseeing due to the way I was picturing this specific use case. I was just trying to find ways to avoid dumping a whole lot of load actions in the App component to initialize all the components if the components could just do it themselves.

**Comment by ivan-kleshnin** [comment]
> You should call the PostActions.loadPosts action from somewhere else. I'd recommend to do this from where you are mounting the App component.

@jankuca as soon as you have big app, loading all dependencies at start can be expensive.
What do you think about different approach: still invoke loading actions at the mounting time, but store, as soon as it receives action, temporarily unsubscribes from action and subscribes again after resolving (completed or failed). With this arch, first action will trigger load, second will omit data loading.
