### ISSUE TITLE
passing options to createActions to define async or sync triggers

### ISSUE THREAD

**Issue by alinz** [spoike/refluxjs#257]
Hello,

I want to use `Reflux.createActions` and create all my action as sync instead of async. At the moment createActions creates each action as async functor.

Do you have any plans to add  `options` argument for `Reflux.createActions`?

At the moment I'm using the following code to achieve the above behaviour.

```js
function createActions (actions, options) {
  return actions.reduce(function (result, name) {
    result[name] = Reflux.createAction(options);
    return result;
  }, {});
}
```

p.s. "thanks for the amazing framework"

Ali

**Comment by spoike** [comment]
Check #249 for status on using options for `Reflux.createActions`.
