### ISSUE TITLE
someAction.then().catch() not working

### ISSUE THREAD

**Issue by Turbo87** [spoike/refluxjs#259]
the [README](https://github.com/spoike/refluxjs#asynchronous-actions-as-promises) mentions that async actions can be used as Promises with `then/catch()` methods, but that doesn't seem to work. when I try to call the `then()` method of one of my actions my browser complains: `Uncaught TypeError: Cannot read property 'then' of undefined`.

**Comment by jankuca** [comment]
You need to use `#triggerPromise()`:

```javascript
var action = reflux.createAction({ asyncResult: true });
var promise = action.triggerPromise();
promise.then(...);
```

**Comment by Turbo87** [comment]
Is that mentioned anywhere in the documentation?

**Comment by srph** [comment]
@Turbo87  Mind posting a snippet of your code?

**Comment by spoike** [comment]
Yes this is a duplicate of #216
