### ISSUE TITLE
Joins - Using the listener instance methods

### ISSUE THREAD

**Issue by timarney** [spoike/refluxjs#261]
Looking at the docs ... with the following code, when the trigger happens should the data passed end up being an array with each index being the last value passed to each action? 

i.e. // `gainHeroBadgeStore` will now asyncronously trigger `[["docks"],["offices",3],["seedyletter"]]`.

From the docs:
```javascript
actions.disarmBomb("warehouse");
actions.recoverData("seedyletter");
actions.disarmBomb("docks");
actions.saveHostage("offices",3);
```
```gainHeroBadgeStore` will now asyncronously trigger `[["docks"],["offices",3],["seedyletter"]]`.

When I try this I only seem to get the value from action 1 being passed back.
http://jsbin.com/taraku/1/edit?html,js,console,output

**Comment by spoike** [comment]
Do note that the handler is getting the whole array as arguments. Check the edit: http://jsbin.com/fazepozopi/2/edit

**Comment by timarney** [comment]
I see thanks for clarifying that.
