### ISSUE TITLE
preEmit can return multiple values???

### ISSUE THREAD

**Issue by alinz** [spoike/refluxjs#264]
Hello,
I had a problem with `preEmit` function. I have some how sorted it out but I want to ask people how would someone do it.

So, here's the problem:
I have an action which gets 3 arguments.

```js
var myAction = Reflux.createAction();

myAction.preEmit = function (val1, val2, val3) {
    // do some minor changes.
};

myAction('Hello', 1, 2);
```

now inside preEmit I wanted to change val1 but I don't want to change the rest of the arguments. Based on my understanding, if you return a value from preEmit it will be pass to subsequent recipients. But what about val2 and val3?

So after couple of experiments I came up with the following solution:

```js
myAction.preEmit = function (val1, val2, val3) {
    arguments[0] = val1 + ' world';
    return arguments;
};
```

It is a hacky and ugly solution which is why I was asking for better solution.

I have also seen people wrap their arguments in a single `options` object and pass it around.

Any suggestions???

thanks

**Comment by jankuca** [comment]
It's actually kind-of a valid solution as the `preEmit` method is called as following but you should be just fine returning a simple array.

```javascript
var preResult = this.preEmit.apply(this, args);
if (typeof preResult !== 'undefined') {
  preResult = _.isArguments(preResult) ? preResult : [].concat(preResult);
}
```

```javascript
myAction.preEmit = function (val1, val2, val3) {
    val1 += ' world';
    return [ val1, val2, val3 ];
};
```

This is alright. If you don't know (or don't want to know) the number of arguments, use your approach or the usual...

```javascript
myAction.preEmit = function () {
    var args = Array.prototype.slice.call(arguments);
    args[0] += ' world';
    return args;
};
```

**Comment by spoike** [comment]
Well... that was the thought when preEmit was implemented to map arguments.
