### ISSUE TITLE
PublisherMethods.promise() broken

### ISSUE THREAD

**Issue by Turbo87** [spoike/refluxjs#265]
https://github.com/spoike/refluxjs/blob/master/src/PublisherMethods.js#L62-L68 doesn't work as expected. It seems as if the catch block isn't properly attached because the browser complains: `Unhandled promise rejection`.

If I change that code to either `promise = promise.then(...); promise["catch"](...);` or use chaining `promise.then(...)["catch"](...);` it works as expected, which makes me believe that the `then()` method is not just returning `this`, but something else instead which should be used.

https://github.com/getify/native-promise-only/blob/master/lib/npo.src.js#L235-L258 seems to confirm that.

**Comment by spoike** [comment]
That's a mistake. I thought I commented on that and it got fixed before I merged the IE8 fix from before.
