### ISSUE TITLE
Enforcing Store State?

### ISSUE THREAD

**Issue by abritinthebay** [spoike/refluxjs#268]
Given that `this.state` in Components is *UI State* and that Stores are supposed to be handling *Application State* would it not make sense to have that as something in all Stores as a standard?

It would also enable easy Store querying from Components. ie: `myStore.get("key")` would return the corresponding object key in the Stores state object. Which is, after all, what the Flux docs recommend.

This would make isomorphic applications trivial too (simple `get()` and `setInitialState(data)` methods).

I'm currently doing this via a mixin and it makes consistency *very* easy to achieve.

**Comment by ivan-kleshnin** [comment]
@abritinthebay

> Given that this.state in Components is UI State

This is wrong. Component state is UI State + Store (Application) state which maps from Store to Component.

**Comment by abritinthebay** [comment]
> In Reflux, component state is UI State + [optional] Store (Application) state which is synced between Store and Component. 

That's not true. That's *one way* you can do state in Reflux sure. But then you'd be **not doing Flux architecture** because you're supposed to be separating them *according to the original docs*. That's quite a large point of Flux in fact.

>  If store state is separated from component state it raises a question about how to redraw component on app state change. 

What? That's... so wrong I don't know how to respond. Store state will *always* be separated from Component state. Unless you're doing something *incredibly* bone-headed like cloning the entire Store state across all components and child-components you'll be separating the states.

Plus now you're confusing Store/App State with component props/data. Which is horrifying, frankly.

**Comment by abritinthebay** [comment]
If all you do is dump the entire Store state on a trigger and then dumbly import that into the component state... sure, then you end up with what you just described.

But... I mean, that's utterly counter to Flux as described by every single FB talk on Flux I've ever watched or attended.

**Comment by abritinthebay** [comment]
Thought I'd comment on this part:

>  You're proposing to replace push architecture with pull

Not at all. I'm proposing *adding* a selective pull mechanism in addition to the (totally unchanged) event driven pull system.

Say I have a complex Store and I only want to pull certain data out of it when it's updated: this would let me. Sure I *could* just dump the entire store state into the event and filter it in the Component - but *that's bad application design* because then the Component needs to know about the entire Store state rather than just what is relevant to just itself.

Remember - A Store is not a model, or collection, it's a complex data storage system that holds the app state for that part of the application domain.

**Comment by abritinthebay** [comment]
The `.get(key)` part of my OP was probably the least important part of it anyhow. It's just a minor side benefit.

**Comment by MatthewDavidYoung** [comment]
Pulled in Mori to house store "state". Basically, reused the logic from Fluxy. Really simple mixin that calls trigger with the Clojure keys when something is set in the Mori store. The components listen and check the keys if their is realivant info for the listening function.

**Comment by abritinthebay** [comment]
Right, that's basically what I'm proposing.

An (admittedly simplistic) implementation could look as simple as the following:

```
Reflux.Mixins = Reflux.Mixins || {};
Reflux.Mixins.StoreState = {
	state: {},
	get: function (key) {
		if (typeof key === "undefined") {
			return JSON.parse(JSON.stringify(this.state)); // return deep cloned copy of data
		} else if (typeof this.state[key] !== "undefined") {
			return JSON.parse(JSON.stringify(this.state[key]));
		}
	},
	set: function (key, data) {
		if (typeof key === "object" && typeof data === "undefined") {
			this.state = JSON.parse(JSON.stringify(key)); // assign deep cloned copy of data to whole state object
			this.trigger();
		} else if (typeof key === "string" || typeof key === "number") {
			this.state[key] = JSON.parse(JSON.stringify(data)); // assign deep cloned copy of data to specific key in state object
			this.trigger();
		}
	}
};
```

...and it would go a long way to making many things easier.

Now the above version would have issues with Date objects (it would convert them to string representations) but the State being JSON compatible is perhaps a good idea. 

Anyhow - not saying the above code is what should be in but the idea is more that a central store should be there.

**Comment by spoike** [comment]
I think it's a good idea to have a common store state to store application level state. In my mind it is totally okay to add this to the store as a mix-in, and will make it easier to keep your web app isomorphic.

However when I chain and join stores, I tend not to set any state. The stores in this case work like glorified map/reduce/filter functions. Because of this I haven't yet decided if making `state` in a Store a mandatory thing or if there should be some kind of a seperate `StatefulStore` implementation or have it as a mixin provided by Reflux.

**Comment by abritinthebay** [comment]
Just a thought - React has the React.Addons namespace for optional stuff like this. If I created a PR with the above as an optional mixin would you be amenable to that?

>  Because of this I haven't yet decided if making state in a Store a mandatory thing

Just because it's mandatory doesn't mean you have to fill it with anything. It's just a case if "if you want the Store to be able to be dehydrated or have a `.toString` representation... then that's what you need to do.

I'm not suggesting forcing a specific workflow. If you're chaining and just using triggers to pass data around then this wouldn't impact anything. That workflow would still work.

**Comment by spoike** [comment]
In order to clean up the issue tracker I have to close down all questions. Please use proper communications channels for questions about reflux, such as:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful](https://tf-assets-staging.s3.amazonaws.com/badges/thinkful_repo_badge.svg)](http://start.thinkful.com/react/?utm_source=github&utm_medium=badge&utm_campaign=reflux)
