### ISSUE TITLE
Bacon.fromEvent

### ISSUE THREAD

**Issue by xgrommx** [spoike/refluxjs#269]
Hello @spoike 

Could you please explain me how can I use ```Bacon.fromEvent``` with React and Reflux. For example I have two buttons like (-1) and (+1) and I would like use it with ```scan``` function of Bacon.

**Comment by xgrommx** [comment]
Someone can help me?

**Comment by reggi** [comment]
+1

**Comment by srph** [comment]
I haven't given **Bacon** a try (although I've seen it). Let me give it a shot :smile:

**Comment by srph** [comment]
It really doesn't make sense for me (to use Bacon and React), but here's an attempt (haven't ran the code, too).

```js
var CounterStore = require('../stores/CounterStore');
var CounterActions = require('../stores/CounterActions');

var Counter = React.createClass({
  mixins: [Reflux.connect(CounterStore, 'count')],
  
  getInitialState: function() {
    return { count: 0 };
  },
  
  componentDidMount: function() {
    this.forceUpdate(); // afaicr, refs are not yet available on first render.

    var up = $(React.findDOMNode(this.refs.up)).asEventStream('click');
    var down = $(React.findDOMNode(this.refs.down)).asEventStream('click');
    
    // map up to 1, down to -1
    up.map(1).merge(down.map(-1))
    // accumulate sum
      .scan(0, function(x,y) {
        CounterActions.sum(x + y);
      }.bind(this));
  },
  
  render: function() {
    return (
      <div>
        <h1>{this.state.count}</h1>
        <button ref="up"> Up </button>
        <button ref="down"> Down </button>
      </div>
    );
  }
});
```

**Comment by xgrommx** [comment]
I think this isn't cool example =) maybe @spoike can help us?

**Comment by LongLiveCHIEF** [comment]
This isn't related to directly to Reflux, so unfortunately we're unable to support it within the the "issues" section of this project. Reflux is a standalone tool, although it's currently somewhat tied to React, it's developed in such a way that you can choose what role it plays in your project,

If you choose to use Reflux with Bacon, you have to take on the responsibility to figure out how to implement that yourself. Think about what you're asking, and scale it out to others who are implementing Reflux with `libraryA` or `viewToolB`, and it means we'd have to be familiar with every tool out there, and that's just not possible.

I also echo @srph 's suggestion to hop on the reflux reactiflux channel. I hang out there every day, and it's an active and helpful community for issues just like this.

***

Having said all that, I encourage you to take a [peek at the dependencies](https://github.com/spoike/refluxjs/blob/v0.3.0-alpha/package.json#L33) of the work in progress on the  0.3.-alpha branch. We'll be using a more reactive approach by directly implementing the Observer / Observable pattern in v0.3, and it will introduce compatibility with the `Array#extras` style of development that Bacon.js conforms to.
