### ISSUE TITLE
Duplicated actions?

### ISSUE THREAD

**Issue by henit** [spoike/refluxjs#271]
Reflux is great! Just one question. Must action names be unique, across different stores listening to them?

I have two stores, with to set of actions (Reflux.createActions), so four different files.One store listen (listenables) to the actions created in one action file, the other store listen to the actions from the other action file. I have verified that they refer to the correct files. However, both sets of actions have an action with the same name. When I call this action somewhere in the application, the corresponding handler is called in both stores, not just the store that listen to the actual action file which I called the action on.

Hope the explenation above was sensable, I could make a code example if needed. So the question is, does Reflux require all aciton names listened to by different stores to have unique names, and thats why I get the duplicated action handler calls in my case, or must there be some other reason for this?

**Comment by spoike** [comment]
> Must action names be unique, across different stores listening to them?

Nope, not in the example you've given. The actions are running their own instance of the eventemitter so they're doing independent events.

The only time naming will matter (to my knowledge) is if you put two actions objects that have same name on actions into the `listenables`. It won't throw an error, instead the last listenable's action of the same name will be used to bind with the appropriate store method IIRC.

**Comment by henit** [comment]
So if I understand you correctly, a structure like this:

actions1.js

    module.expors = Reflux.createActions({
        "doSomething",
        "action2"
        // ...
    });

actions2.js

    module.exports = Reflux.createActions({
        "doSomething",
        "action3"
        // ...
    });

store1.js
    
    var actions = require('path/actions1');
    
    module.exports = Reflux.createStore({
        listenables: actions
        onDoSomething: function() {
            // ...
        }
    });

somePartOfTheApplication.js
    
    var actions1 = require('path/actions1');
    var actions2 = require('path/actions2');

    // This will run onDoSomething in store1.js:
    actions1.doSomething();

    // While this will not?
    actions2.doSomething();

So the actual place where the action was created is what is unique? If I do a Reflux.createAction('doSomething'); outside of the action file that store1.js is listening to, triggering this aciton will not cause onDoSomething in store1.js to run even if the action name is the same?

**Comment by jankuca** [comment]
Of course it won't. You should not think about actions as of string identifiers. Action is just an emitter on which you can trigger a single type of an event (listenable via `#listen()`).

```
var obj = reflux.createActions([ 'name1', 'name2' ])
```
is just a shortcut for
```
var obj = {
  name1: reflux.createAction(),
  name2: reflux.createAction()
};
```

Distinct calls to `#createAction()` know nothing about each other and always create and return a new emitter. Triggering one does not affect the other in any way. You are listening to a unique instance, not to a "type" of an action.

**Comment by henit** [comment]
Ok. In that case, there must be some reference mixup in my application, because listening functions in two different stores where both triggered when just one of the two actions (with the same name) from two action-returning files where called.

**Comment by jankuca** [comment]
Oh actually I missed your point completely.

Your mistake is that you need to have both `actions1` and `actions2` as registered listenables on the store.

```
reflux.createStore({
  listenables: [ actions1, actions2 ]
})
```

**Comment by henit** [comment]
You didn't miss the point, my last explenation was probably unclear.

However, I found out what caused my application to call the listening function in both my stores when I called the action that was only listened to by one of the stores. The problem is called Browserify. It suddenly decided to reference one file to another, even if the require statement for the two files (my two action creating files) point to two completely different files. Here is a slightly modified cutout of my Browserify-build. As you can see, the second actions-file just require the first one. I have not found any logical reason in my code for why it does this. But this caused my second store to listen to the actions from the first action file instead of the second, causing the described problem.

    "/path/to/first/actions-file.js":[function(require,module,exports){
    
    var Reflux = require('reflux');
    
    module.exports = Reflux.createActions({
        // ...
    });
    },{"reflux":"/../node_modules/reflux/index.js"}],"/../path/to/second/actions-file.js":[function(require,module,exports){
    module.exports=require("/path/to/first/actions-file.js")
    }

I have been thinking of switching from Browserify to WebPack for some time now, mabye this is the time to do just that.
