### ISSUE TITLE
How to enforce order of execution of action listener callbacks in stores?

### ISSUE THREAD

**Issue by jeffcharles** [spoike/refluxjs#272]
Hi,

I've got a couple stores listening for a given action. One store's callback needs to execute before the other's since the one I'd like to run second performs some clean-up on state required by the one I'd like to run first. If I were using Flux, I'd use `waitFor` in the action callback in the second store pointing at the first store's dispatch token to enforce the order of the callbacks. What's the equivalent mechanism in Reflux?

**Comment by spoike** [comment]
There are two ways:

* Let stores listen to the stores they need to wait for (for sequential data flows) https://github.com/spoike/refluxjs#listening-to-changes-in-other-data-stores-aggregate-data-stores
* Let stores listen to a join (for parallell data flows) https://github.com/spoike/refluxjs#joining-parallel-listeners-with-composed-listenables

**Comment by jeffcharles** [comment]
I experimented a bit with both methods and they seem to not work in different ways for me. For the first one, I had the following code:

```
onQuestionAddDone: function() {
        this.listenTo(pollStore.store, function() {});
        this.questionBeingAdded = false;
        this.addQuestion = '';
        this.questions[this.newQuestionId] = {};
        this.trigger(this);
},
```

`pollStore`'s (the store I'm listening to) `onQuestionAddDone` still ran first. There was also an error raised when I didn't provide a callback function. I wanted to forgo the function since I don't care about the other store's state here, I just need to ensure it's callback has fired first. Using the `listenTo` in `init` is a no-go for me since the two stores are dependent on each other so the store isn't populated inside `init` yet. I also may want certain action handlers in `pollStore` to fire after the ones in this store have fired (referencing each store in the other's `init` definitely won't work).

The second approach raises `Cannot create a join with less than 2 listenables!` when I try using it:

```
init: function() {
        this.joinStrict(actions.answerAddDone, this.doneAddingAnswer);
        this.joinStrict(actions.questionAddDone, this.doneAddingQuestion);
        this.questions = {};
},
```

How do these APIs work with circularly dependent stores, by which I mean stores which read data out of each other?

**Comment by LongLiveCHIEF** [comment]
There is a bug in https://github.com/spoike/refluxjs/blob/master/src/joins.js#L38 that is contributing to this. The logic says "less than 2", but the code uses `< 2 `, which will throw an error if you use 2.

I'm refactoring a few things around listening to stores at the moment, and it will impact the answer to this question. Things will be a bit *more* asynchronous.
