### ISSUE TITLE
Stores passed in getChildContext instead of Singletons

### ISSUE THREAD

**Issue by nambrot** [spoike/refluxjs#274]
I'm new to (Re)Flux and currently trying to get it to work server side with react-router. Obviously, I currently can not use the very convenient Connect Mixin as it relies on components being mounted, but also because referring to Singletons is complicated on the server. I unfortunately do not know enough (yet) about the architecture of both and while I overall like Reflux the best (less boilerplate and sensible defaults), I really like Flummox's strategy of passing down the Stores as contexts. This would allow both the use of Stores on the server, as well as make it easier to hydrate the stores, right?

**Comment by Strajk** [comment]
@nambrot can you please elaborate on "hydrate the stores"? I'm new to Flux so I'm trying to understand the common problems it's implementations are trying to solve

**Comment by nambrot** [comment]
I'm new as well, but I believe hydrating refers to the process of populating a Store with data that you have gathered on the server and somehow embed in the server response, so that you avoid re-fetching

**Comment by Strajk** [comment]
I thought it's somewhat specific for Flux... thanks, I found it also answered here: http://stackoverflow.com/questions/6991135/what-does-it-mean-to-hydrate-an-object

**Comment by spoike** [comment]
In order to make Reflux objects as instances instead of singletons, make a simple factory for them by wrapping them in a function.

```javascript
var MyStoreFactory = function() {
  var myStore = Reflux.createStore({ /**/ });
  return myStore;
};
```

To resolve the instances you roll your own DI module. Or you can use libraries such as [`diez`](https://github.com/ericclemmons/diez) to do that for you, like this example:

```javascript
diez.register(MyStoreFactory, ['myStore']);
```

To retrieve the instance in `diez` do it like this:

```javascript
var myStore = diezContainer.get(MyStoreFactory);
```
