### ISSUE TITLE
Binding a component to global stores/actions VS passing it stores/actions VS passing it data/funcs as props?

### ISSUE THREAD

**Issue by jimbolla** [spoike/refluxjs#278]
Looking at adding Reflux into my app. One thing I see in the examples is that the components seem to be bound globally to action/store singletons. For example

    // UserList.jsx
    var usersStore = require('./UsersStore.jsx');
    var UserList = React.CreateClass({
        mixins: [Reflux.connect(usersStore)],
        // ...
    });
    module.exports = UserList;

Now my parent component, UserSearchScreen, doesn't have to worry about the specifics of passing it data, because it it just triggers actions that cause the store to load data and send it to the UserList component. That's cool. But now UserList is bound to that particular store. I can't, for example, bind it to another store that loads and operates on users in a different way. Or I can't have 2 instances of the same component each bound to their own instance of the UsersStore (for example, if I had a UI with left/right comparisons)

Should child components that are meant to be reusable not be Reflux-aware and rely on "data-down, actions-up" React-only flow? Or should the parent component be responsible for passing stores/actions to child components? If they should be passed to the child, should I set them as props, creating a lot of `actions={actions} store={store}` code in my JSX, or should I use a closure like so:

    // UserList.jsx
    module.exports = function(store, actions) {
        return React.createClass({
            mixins: [Reflux.connect(store)],
            // ...
        }
    }

    // UserSearchScreen.jsx
    var UserList = require('./UserList.jsx')(store, actions);
    // ...

Looking for guidance...

**Comment by jankuca** [comment]
My recommendation is to stay away from using mixins and instead pass store instances to your controller-view components via props. Global state should be prevented.

**Comment by spoike** [comment]
Huh. Never thought about passing store instances through props. I need to try that sometime. Thanks for the tip @jankuca

**Comment by ChadMartinson** [comment]
@jankuca are there any examples of what that would look like? passing store instances through props.
