### ISSUE TITLE
Reflux error handling

### ISSUE THREAD

**Issue by dev-tim** [spoike/refluxjs#280]
Hello! 
I'm diving in to Reflux and got question about handling error in Reflux application.
For example I have store where I perform ajax request that can be failed. 

How I would notify my component about error happened?
Pass error data alongside with model? Or listen to action in component? 

What is the best practice for Reflux application?

**Comment by ivan-kleshnin** [comment]
I think component should just render itself in different ways depending on state. Consider detail page for example. If `this.state.model` is object – state is loaded and renderable. If `this.state.model` is `undefined` – state is under progress, render <Loading/> component. If it's string – treat it as error message. 

In this way you can render your component tree right from the start, avoiding blank screens.

**Comment by jankuca** [comment]
You should definitely expose the error that happened (either the actual message or an enum key of which the component can create an appropriate representation) in some way. I'd have a `#getCurrentOperation()` method on my store or in the case of a queue (an upload/download queue for instance), I am listing failed items alongside those queued and in progress. They just have a `state: ERROR` and an `error` property with details.

**Do not listen to actions in components.** Only listen for *change* events on stores.

**Comment by max-zelinski** [comment]
I've the same problem: passing error from a store to React component. Can triggerPromise help somehow in this case?

**Comment by erikvinicius5** [comment]
Whenever I have an action which will trigger an ajax call I create another with the same name `+ 'Fail'`. Like `'changeXToY'` and `'changeXToYFail'`.

I call the action and the store listening to it updates the data and makes the ajax call sending along an object with everything I'm changing (the old values). 

If I get an error, I call the fail action (from within the ajax error function with the object carrying the old values), which is being listened by both the Store and the Component. The Store then revert the changes (specified by the object I sent) and the Component notifies the user about the error.

**Comment by vitalybe** [comment]
@ivan-kleshnin
>  I think component should just render itself in different ways depending on state. 

I find it rather constricting to put everything in the global store state. For example, consider a case in which we display product details and allow a user to rename the product. The details of the product are in the store, e.g:

    {
        name: "product a",
        price: 10,
    }

Once the user tries to rename it RENAME_PRODUCT action starts. Once the rename is successful, the details in the store should update. If we have a failure however, we could store it in the store, like so:

    {
        name: "product a",
        price: 10,
        renameOperationResult: errorObject
    }

But do we really want to do that? It seems wrong to pollute the store state with information that will be only used in a single component. 

How about something like that?

    actions.login(email, password).catch(function() {
        this.setState({ renameOperationResult: errorObject });
    });

We don't pollute the store state that way, but it comes at the cost of breaking the whole flux-one-directional principle.

**Comment by vitalybe** [comment]
I've made a question on that subject in [StackOverflow](http://stackoverflow.com/questions/30902512/how-to-keep-local-component-data-e-g-spinners-errors-outside-of-flux-stores)
