### ISSUE TITLE
This seems to be a pre-built javascript file webpack+npm warning

### ISSUE THREAD

**Issue by snario** [spoike/refluxjs#283]
When I start `webpack` I always get this warning after `npm install reflux --save`ing and `require('reflux');`. This is never an issue with other frameworks but it seems like `npm` is looking in the `dist` folder instead of `src`. Is this something that can be configured within `refluxjs` or something else I should be doing on my end? Just want to get rid of this warning and use it correctly.

```
WARNING in ./~/reflux/dist/reflux.js
Critical dependencies:
1:437-444 This seem to be a pre-built javascript file. Even while this is possible, it's not recommended. Try to require to orginal source to get better results.
 @ ./~/reflux/dist/reflux.js 1:437-444
```

**Comment by spoike** [comment]
Are you really sure you don't have some configuration anywhere that is pointing out the pre-built file?

Can't help you much there since I'm not using webpack at the moment.

**Comment by snario** [comment]
No configuration whatsoever, the only things I have done are:

`npm install reflux --save`

followed by

`require('reflux');` in my application code. The error happens on `webpack -d`. In my `webpack.config.js` the only thing that could affect it would be:

```
    resolve: {
        root: __dirname,
        modulesDirectories: ['node_modules', 'bower_components']
    }
```

**Comment by thatotherone** [comment]
Do you by chance have something like
```javascript
        new webpack.ResolverPlugin([
            new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])
        ])
```
in your `webpack.config.js`? It's part of several "react starter kits". If you do, you can either delete it if you don't use bower or replace it with

```javascript
        new webpack.ResolverPlugin([
            new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("package.json", ["main"]),
            new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])
        ]),
```
To prioritize cjs/npm `package.json` over `bower.json`

**Comment by snario** [comment]
The closest I have to that is

```
        new BowerWebpackPlugin({
            manifestFiles: 'bower.json',
            excludes: /(.*\.less|.*\.css)/,
        }),
```

**Comment by zachwood** [comment]
If you use the BowerWebpackPlugin, webpack seems to be pulling it from reflux's bower.json file here:

https://github.com/spoike/refluxjs/blob/master/bower.json#L9

I think it's probably safe to assume you don't want webpack looking for bower requirements inside of your node_modules directory, so you'll want to tell webpack to exclude it.

**Comment by snario** [comment]
That makes sense, works fine too, thanks.
