### ISSUE TITLE
How do I listen to children actions with the `listenables` attribute in a store?

### ISSUE THREAD

**Issue by snario** [spoike/refluxjs#284]
The listenables shorthand in stores (https://github.com/spoike/refluxjs#the-listenables-shorthand) let's me just pass in a simple action and it figures out the naming for you. What if I have an action with children `completed, failed` as shown in the README (https://github.com/spoike/refluxjs#asynchronous-actions)?

What should the method be called?

**Comment by bobsamuels** [comment]
If you're using async:true or manually creating "completed" and "failed" children you should just listen for onSomeAsyncActionCompleted and onSomAsycActionFailed within your store.

**Comment by snario** [comment]
Ah okay makes sense, I would add that to the README.

**Comment by spoike** [comment]
Yeah, the README needs to be updated with an example of this.

Either that or a API docs section would be nice to have as well.

**Comment by kevinsimper** [comment]
That definitely would be great to have that, that part is not really clear :+1:
