### ISSUE TITLE
There is a roadmap somewhere? 

### ISSUE THREAD

**Issue by maxguzenski** [spoike/refluxjs#285]
There is a roadmap somewhere? 
I am especially interested if there is reflux plans to provide or recommend an architecture for the main problems such as paging, "loading spin", centralized error handler, generic errors (like timeout, not found, permissions), data rollback (when server return error)

All thins look to be a very common issue on all projects and it seems that no one is trying to fix it.

**Comment by spoike** [comment]
There is no actual roadmap and no actual 1.0 planned as of yet. The goals I have for reflux are quite modest. I want Reflux to be a small, simple and extensible pub-sub library.

I suggest anyone who are interested to work on extensions as separate projects and npm packages. Let me know if there is any way, other than mixins, to make it easy to extend reflux or integrate it with other libraries.

**Comment by FractalizeR** [comment]
@spoike How do we mix something into Reflux itself? For example, I would like to introduce my own version of `connect` and `connectFilter` with new names. Should I just overwrite those properties on a global Reflux object with my new derivators?
