### ISSUE TITLE
How to test trigger() function by jest

### ISSUE THREAD

**Issue by tchcxp** [spoike/refluxjs#287]
Basically in the test I need to make sure the trigger() function is called, and the parameters passed are all correct.

Normally we mock a function and make sure this function is called with parameters, however in this case, I don't think we are able to mock the trigger function.

Thanks in advance.

**Comment by srph** [comment]
I think *spies* would come in handy in this situation.

**Comment by tchcxp** [comment]
@srph  Thanks for response. Do you mean this: https://www.npmjs.com/package/spies?

Thanks.

**Comment by spoike** [comment]
@tchcxp I'm pretty sure you can create test spies in Jest already, though they're just called mocks in Jest. See http://facebook.github.io/jest/docs/automatic-mocking.html#content

Basically you can mock the trigger function by just overriding the trigger function in your store. Something like this:

    myStore.trigger = jest.genMockFunction();

And then in your assertion make sure it's been called, like this:

    expect(myStore.trigger.mock.calls.length).toEqual(1);

**Comment by tchcxp** [comment]
@spoike 

Thanks mate. Misspelled the function name so did not test it successfully.

Yes, `myStore.trigger = jest.genMockFunction();` is working. Thanks again.

Also, sometimes we need to make sure the function called with correct parameters, so we can use `.toBeCalledWith()` in the assertion.
