### ISSUE TITLE
0.2.6 IE8 issue

### ISSUE THREAD

**Issue by deniss-muhla** [spoike/refluxjs#288]
Hello!
Unfortunately we need to support IE8 browser.
After upgrading to 0.2.6 version we have error in "utils.js" file "extend" function:
...
var propertyDescriptor = Object.getOwnPropertyDescriptor(source, prop);
Object.defineProperty(obj, prop, propertyDescriptor);
...

Object.getOwnPropertyDescriptor(source, prop) returns 'undefined' for 'bind' property and Object.defineProperty throws exception.

This occures when Reflux.createActions method called.
We use "es5-shim;es5-sham".

**Comment by spoike** [comment]
Related to #286

**Comment by deniss-muhla** [comment]
Have tried fix proposed in https://github.com/spoike/refluxjs/pull/286 fix.
This will solve this https://github.com/spoike/refluxjs/issues/288 issue.
Thanks!
