### ISSUE TITLE
Testing stores without jest

### ISSUE THREAD

**Issue by kentor** [spoike/refluxjs#289]
I'm trying out karma + jasmine + webpack for testing my react app with reflux (following https://www.codementor.io/reactjs/tutorial/test-reactjs-components-karma-webpack), and it's working out great for simple components and models. Jest was just too slow for me.

The problem with this setup is that stores are singletons and they contain state that carries over to each test. This makes it difficult to predict when tests run in different order, and it really made me regret using singletons in the first place.

We could write a method to reset the store but this is very error prone...

I was wondering if anyone else had to deal with this?

**Comment by jankuca** [comment]
Singletons, when implemented as static or if they are being fetched by the dependant, are evil almost in any case but especially in combination with testing.

The answer is DI. Inject stores either by props or as constructor arguments.

**Comment by kentor** [comment]
Hmm figured something out with clearing the webpack module cache before each test. Seems to work.
