### ISSUE TITLE
Trouble asserting action mock was called in jest tests

### ISSUE THREAD

**Issue by jehoshua02** [spoike/refluxjs#292]
I'm having trouble asserting that an action mock was called by my component in my jest tests.

I've submitted an issue over at [jest](https://github.com/facebook/jest/issues/306) and submitting here because it seems to be related to both.

My issue over at jest contains links to source code and steps to reproduce.

**Comment by spoike** [comment]
Some handy tips at #210, #218, and #254.

Basically, actions are async and you could mock the action's trigger function. Before doing any assertions, with e.g. `expect`, you may need to run `jest.runAllTimers();` to fast forward the timers since actions are deferred by default.

**Comment by jehoshua02** [comment]
Um ... too complicated. Since I'm calling `Actions.REQUIREMENT_SAVE` as a simple function, I should be able to mock it out with a plain old synchronous function.

**Comment by jehoshua02** [comment]
And it seems there is an issue with jest itself [not mocking out things as it should](https://github.com/facebook/jest/issues/306#issuecomment-81463843).

**Comment by jehoshua02** [comment]
I think I might end up using [rewire](https://github.com/jhnns/rewire) instead of jest. We'll see what jest maintainers figure out.

**Comment by jehoshua02** [comment]
@spoike 

#210: I added reflux to the list and still having problems.
#218: I tried running all timers and still having problems.
#254: My desire is to mock out the Actions object altogether. Reflux shouldn't be involved at all.

I don't think this is a problem with reflux. This must be an issue with jest. Closing issue.
