### ISSUE TITLE
getting async data from store or through actions?

### ISSUE THREAD

**Issue by maxguzenski** [spoike/refluxjs#295]
Hi,
How you guys are deal with getting data from store that maybe need call server? For example, I have a UserListStore where user can sort data by name or by createdAt. If UserListStore has all page loaded, it need call server and ask for a paginated sorted version. But in case it already has all pages in memory, it can sort by its own.

Idea 1 - logic on action. This idea put reference of store inside a action, that dont like to be a good ideia (I dont think that actions should 'know' about stores)

```javascript
sortAction.listen(function(sortOrder) {
  if !UserListStore.canSortBy(sortOrder) {
    // callAPI(sortOrder) and send a this.completed
  }
});
```

idea 2 - Logic inside store

```javascript
// inside a React component, get data from store
// store will sort and trigger change OR call server API and trigger change
onClick: function() {
  UserStoreList.getSortedBy('...');
}
```

**Comment by maxguzenski** [comment]
idea 3 - Combine actions and store

```javascript
// actions has sortBy, load (that make a api call) and loadCompleted
UserListStore = Reflux.createStore({
onSortBy: function(sort) {
  // or sort and call trigger
  // or call actions.load({sort: sort});
} 

onLoaded: function(data) {
  this.data = data;
  this.trigger(this.data);
} 
});

// in react component
onClick: function() {
  actions.sortBy('...');
}
```

**Comment by mschipperheyn** [comment]
I also found a special case in Reflux, where you can call a login action and get a Promise returned if the resulting actions are "completed" and "failed". 

   //Action component
    var LoginActions = Reflux.createActions({
	"login": {asyncResult:true,children:["completed","failed"]}
    });

    [...]

    	LoginActions.login.listen(function(email,password){

		var instance = this;

		fetch(config.urls.loginUrl,{
			method:'post',
			headers:rConfig,
			body:JSON.stringify({
				username:email,
				password:password
			})
		})
		.then(status)
		.then((response) => response.json())
		.then((json) => {


			var user = json.user;
			
			this.completed({
				email:user.email,
				token:user.token,
				userId:user.id,
				img: user.photo,
				photoDir : user.userDirectory,
			});
		});

       //LoginScreen
	LoginActions.login.listen(function(email,password){

		var instance = this;

		fetch(config.urls.loginUrl,{
			method:'post',
			headers:rConfig,
			body:JSON.stringify({
				username:email,
				password:password
			})
		})
		.then(status)
		.then((response) => response.json())
		.then((json) => {


			var user = json.user;
			
			this.completed({
				email:user.email,
				token:user.token,
				userId:user.id,
				img: user.photo,
				photoDir : user.userDirectory,
			});


		})
		
	[...]

	LoginActions.login(value.username,value.password)
        .then(status)
        .catch(function(err){
        
        [...]

**Comment by spoike** [comment]
In order to clean up the issue tracker I have to close down all questions. Please use proper communications channels for questions about reflux, such as:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful](https://tf-assets-staging.s3.amazonaws.com/badges/thinkful_repo_badge.svg)](http://start.thinkful.com/react/?utm_source=github&utm_medium=badge&utm_campaign=reflux)
