### ISSUE TITLE
What should you trigger?

### ISSUE THREAD

**Issue by kevinsimper** [spoike/refluxjs#298]
I feel what i had most problem grasping, was what you should trigger in the Reflux Stores.

All the examples is very simple like: 
```
this.trigger({
  currentStatus: status
})
```

But later when you try to add more listeneres in a React component, you found out that a store triggers every event and not only the one you listen to.

```
// You would think that it would only trigger when "status" change
this.unsubscribe = statusStore.listen(this.onStatusChange);
// But then you try this and it also triggers when status change
this.unsubscribe = statusStore.listen(this.onCommentsChange);
```

## So solution:

I think the docs should mention that you should trigger the whole Store's output every time, and not just different part of data and the change the docs to say:

```
statusStore.listen(this.onChange);
```

**Comment by jankuca** [comment]
The component should actually pull the data it needs by itself. You can pass some kind of a change summary as an argument to `trigger()` but that should not be the way you pass the actual state to the component. At least that's what I would describe as a good practice.

**Comment by kevinsimper** [comment]
@jankuca How would that look? :) Do you have an example?

There is an example in the docs that triggers all the data like this
https://github.com/spoike/refluxjs#listening-to-changes-in-other-data-stores-aggregate-data-stores

**Comment by jankuca** [comment]
```javascript
init: function () {
  this.listenTo(store, this.handleChange)
},
handleChange: function () {
  // use a getter on the store to get the data
  this._state.someKey = store.getWhatINeed();
  this.trigger();
},
// provide a getter for a possible dependant to use
getSome: function () {
  return this._state.someKey;
}
```

Quite simple really. You might want to pass an ID of a changed record in the store to trigger but I'd recommend you just let the component (or the dependant) get what it needs on its own via getters.

```javascript
handleChange: function (changed_item_id) {
  this._names[changed_item_id] = store.getName(changed_item_id);
  this.trigger();
}
```

**Comment by jankuca** [comment]
If you wanted to use different handlers for different trigger payloads, you'd need to have some kind of a routing done in the main handler.

```javascript
handleChange: funciton (summary) {
  switch (summary.type) {
  case 'status': this.handleStatusChange(summary);
  case 'comments': this.handleCommentChange(summary);
  }
}
```

**Comment by akre54** [comment]
We do something closer to the following:

```js
var getStateFromStores = function() {
  return {
    widgets: WidgetStore.getWidgets(),
    fobs: FobStore.getFobs(),
    unreadFobs: FobStore.getUnread()
  };
};

var App = React.createClass({

  mixins: [
    Reflux.listenTo(WidgetStore, 'onStoreChange'),
    Reflux.listenTo(FobStore, 'onStoreChange'),
  ],

  getInitialState() {
    return getStateFromStores();
  },

  onStoreChange() {
    this.setState(getStateFromStores());
  },
  
  render() {
    <WidgetContainer widgets={this.state.widgets} />
    <Fobs fobs={this.state.fobs} unread={this.state.unreadFobs} />
  }
});
```

Our stores look like this:

```js
var _fobs = [],
    _unreadFobs = {};

var FobStore = Reflux.createStore({
  addFob(fob) {
    _fobs.push(fob);
    _unreadFobs[fob.id] = true
    this.trigger();
  },

  markAsRead(fob) {
    _unreadFobs[fob.id] = false;
    this.trigger();
  },

  getFobs() {
    return _fobs;
  },

  getUnread() {
    return _unreadFobs;
  }
});
```

This has the advantage of keeping our stores nice and clean, and our components always get the right data at the time from the stores.

**Comment by kevinsimper** [comment]
@jankuca @akre54 Thank you very much for the examples! It gave me something to think about and they do see like better solutions! I wish the examples looked like these.
