### ISSUE TITLE
Remove native-promise-only shim from dependencies

### ISSUE THREAD

**Issue by nuschk** [spoike/refluxjs#302]
Reflux includes a Promise shim (native-promise-only), which is certainly a very acceptable choice. Still, React's policy in this regard is quite different:

https://facebook.github.io/react/docs/working-with-the-browser.html

Quote: 
 > In addition to that philosophy, we've also taken the stance that we, as authors of a JS library, should not be shipping polyfills as a part of our library. If every library did this, there's a good chance you'd be sending down the same polyfill multiple times, which could be a sizable chunk of dead code. If your product needs to support older browsers, chances are you're already using something like es5-shim.

It would probably make sense to converge on this philosophy and not include the shim anymore. I know, it's such a small library, but still... In one of our projects we were are using https://github.com/jakearchibald/es6-promise for non-React code and thus are already shipping two different implementations.

**Comment by spoike** [comment]
Yeah. It's a mistake. It should be removed, and let anyone shim the functionality in with whatever they want.

**Comment by nuschk** [comment]
Thank you!
