### ISSUE TITLE
Sending actions from onChange, Reflux drops events while Flux is working fine.

### ISSUE THREAD

**Issue by cluxton** [spoike/refluxjs#305]
Hi,
I've been playing around with a basic form and comparing the performance of Reflux vs Flux. While I really like the simplified stores and action creation in Reflux, it does not seem to perform as well as Flux.

The basic flow looks like this: inputs onChange event triggers a "valueUpdated" action. The store listening to this updates its data and triggers an update back to the component, which then sets the value attribute of the input.

The problem I have run into is that when I type quickly into the input, some key presses are lost. (e.g. type "abababababab" very quickly and you'll get something like "ababbabaaba").

Here is an example that can recreate the issue (I'm testing in chrome):
```js
var React = require('react');
var Reflux = require('reflux');

var FormActions = Reflux.createActions([ "updateValue"]);

var _value;
var FormStore = Reflux.createStore({
  listenables: [FormActions],
  
  getInitialState: function() { 
    return this.getAll(); 
  },

  getAll : function(){
    return {
      value: _value
    };
  },
  
  onUpdateValue: function(value) {
    _value = value;
    this.trigger(this.getAll());
  }
  
});

var FormTest = React.createClass({
  mixins: [Reflux.connect(FormStore)],

  onChange : function(e) {
    FormActions.updateValue(e.target.value);
  },

  render: function() {
    return <input name="field" value={this.state.value} onChange={this.onChange} />
  }
});

module.exports = FormTest;
```

```
//package.json
...
"react": "^0.12.2",
"reflux": "~0.2.7",
...
```

If I recreate the same experiment using regular Flux, everything works fine and not a single change event is lost. Am I connecting my component, action and store together correctly?

**Comment by spoike** [comment]
This is because reflux actions and stores are async. You can set them to be sync, but it's easier to invoke the `updateValue` action either when on the input's `onBlur` event or by debouncing/throttling the update event (so it updates when you've stopped typing).

**Comment by cluxton** [comment]
Ah, looks like I missed the part of the readme explaining the synchronous actions... Thanks! 

Debouncing wasn't working for me because I'm setting the `value` attribute on the input. Synchronous actions are the only way I could reflect user input in the store <i>and</i> modify the input's value from the store (e.g. in response to an 'undo' action)

For anyone else with the same problem, I changed the action definition to this :
```js
var FormActions = {
    updateValue: Reflux.createAction({sync:true})
};
```
