### ISSUE TITLE
onClick Action with parameter triggers infinite loop?

### ISSUE THREAD

**Issue by remimarsal** [spoike/refluxjs#306]
Hey guys!

In one of my components, in the render method I have several buttons with an onClick attribute. Everything is fine if I just have 
`onClick={Store.Action}`

But if I set a parameter relative to that button as in 
`onClick={Store.Action(parameter)}` 
or even just 
`onClick={Store.Action()}`
then the component callback for store status update is called as soon as the page loads and indefinitely, as if the store status was changing even though nothing has been clicked.

What am I doing wrong? 
AFAIK, it only happens in the render method but this is where I would like to pass the action parameters for that specific item.

Thanks for your help!

**Comment by remimarsal** [comment]
I found a workaround by using an additional store B and setting up the first store A to listen to changes in a list of stores B. Thus said, I still don't understand why we can't pass parameters to actions in the render method..

**Comment by jankuca** [comment]
There's a huge difference between these two expressions: `fnName` and `fnName()` – one just references a function and the latter also invokes it. If you want to set a handler with predefined parameters; this is called partial application and is done via `Function#bind()`:

Given a function `a`, `a.bind(context, 123)` returns a new function which when invoked calls `a` with `123` as the first parameter. It is possible to also provide additional arguments to the new function and those will be passed to the function `a` after the specified first argument (`123`).

```javascript
var a = function (x, y, z) { console.log(x, y, z); };
var b = a.bind(null, 123);
b(); // 123, undefined, undefined
b(567); // 123, 567, undefined
```

For methods, we need to consider and keep the context (the object on which the method is invoked and which should be referenced as `this` inside the method). `obj.method` can be partially applied while keeping the context as `obj.method.bind(obj, arg1, arg2...)`.

    onClick={Store.Action)}
    // which is the same as
    onClick={Store.Action.bind(Store.Action)}
    // but this makes what you need possible:
    onClick={Store.Action.bind(Store.Action, value)}

This is rather verbose I'd say thus I'd recommend having a separate handler in the form of an actual component method. You can either make a special convenience method on the component:

```
handleClick: function (param) {
  Store.Action(param);
},
render: function () {
  ...
  onClick={this.handleClick.bind(this, value)}
  ...
}
```

…or if `Store.Action` is just a semantic composition and it is actually a functor returned by `Reflux.createAction()`, the context is handled correctly internally and it is possible to simply call `Store.Action.bind(null, value)`.

**Comment by remimarsal** [comment]
Awesome answer! It all makes sense now... :))  Thanks
