### ISSUE TITLE
What is the best way to set the order of which stores receive an action?

### ISSUE THREAD

**Issue by bluejamesbond** [spoike/refluxjs#309]
New to the flux/reflux system. Any advice would be appreciated. Given an action A and Store B and Store C, how can Store B responds to action A followed by Store C in that particular order. How do we deal with asynchronous situations.

**Comment by FractalizeR** [comment]
I do not think it is a good idea to rely on any particular order of handling actions if even this is possible. It makes your code hard to read since reader will now have to deduce, that order is important.

**Comment by LongLiveCHIEF** [comment]
see the [Listening to changes in other data stores (aggregate data stores)](https://github.com/spoike/refluxjs#listening-to-changes-in-other-data-stores-aggregate-data-stores) of the readme.

If you need more help, I'd suggestion using one of the help channels referred to in the readme. I myself am usually reachable via the reactiflux channel most times. A more specific answer would really depend on your specific data and application.

>For questions please use the following communication channels:
>1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
>2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
>3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
