### ISSUE TITLE
Standard way to extend Reflux?

### ISSUE THREAD

**Issue by FractalizeR** [spoike/refluxjs#310]
Sometimes we need to introduce new features into Reflux library, which may not be suitable for the core. What is a standard way to mix something into Reflux object?

For example, I have the following Reflux extension now:

```php
Reflux.connectInherited = function( listenable, key ) {
    return {
        getInitialState: function() {
            if ( typeof listenable.getInitialState === "function" ) {
                return listenable.getInitialState ()[ key ];
            } else {
                return {};
            }
        },
        componentDidMount: function() {
            this.extend ( this, Reflux.ListenerMethods );
            var _this = this;
            this.listenTo ( listenable, function( v ) {
                if ( undefined === v[ key ] ) {
                    return;
                }
                _this.setState ( v[ key ] );
            } );
        },
        componentWillUnmount: Reflux.ListenerMixin.componentWillUnmount,

        /**
         * Taken from Reflux utils
         *
         * @param {Object} obj
         * @returns {Object} {*}
         */
        extend: function( obj ) {
            if ( !( typeof obj === "object" && obj !== null) ) {
                return obj;
            }
            var source, prop;
            for ( var i = 1, length = arguments.length; i < length; i++ ) {
                source = arguments[ i ];
                for ( prop in source ) {
                    if ( Object.getOwnPropertyDescriptor && Object.defineProperty ) {
                        var propertyDescriptor = Object.getOwnPropertyDescriptor ( source, prop );
                        Object.defineProperty ( obj, prop, propertyDescriptor );
                    } else {
                        obj[ prop ] = source[ prop ];
                    }
                }
            }
            return obj;
        }
    };
};
```
I'm using pre-built version of Reflux (not `require`ing it from sources). Since `utils` module is declared like
```js
var _ = require('./utils');
```

I cannot reuse it and I ought to duplicate code.

**Comment by LongLiveCHIEF** [comment]
Have you seen [Reflux.StoreMethods](https://github.com/spoike/refluxjs#refluxstoremethods)?

**Comment by FractalizeR** [comment]
Yes, but this is not a StoreMethod. My implementation is a mixin for React component to connect a component to a part of store's state. Semantically it is close to `Reflux.connect()` and I would like it to work the same way.

**Comment by LongLiveCHIEF** [comment]
@FractalizeR are you on gitter or reactiflux slack?

**Comment by FractalizeR** [comment]
@LongLiveCHIEF No, just using ReactJS + Reflux in a 'manual' way ;)

**Comment by FractalizeR** [comment]
Yes, just joined.

**Comment by spoike** [comment]
In order to clean up the issue tracker I have to close down all questions. Please use proper communications channels for questions about reflux, such as:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful](https://tf-assets-staging.s3.amazonaws.com/badges/thinkful_repo_badge.svg)](http://start.thinkful.com/react/?utm_source=github&utm_medium=badge&utm_campaign=reflux)

**Comment by spoike** [comment]
I've opened up utils btw and it will be available at the next release through `Reflux.utils`. See also #253. 

Currently if you were using the npm package I'm sure you can require the internal utilities with `require("reflux/src/utils")`.

Regarding opening up for mixing in functionality in Reflux, I'm still pondering on that. At the moment, the only way is to add to the Reflux object like @FractalizeR did above.

**Comment by FractalizeR** [comment]
Thanks!
