### ISSUE TITLE
Fix Refux.connectFilter mixin

### ISSUE THREAD

**Issue by shadeglare** [spoike/refluxjs#319]
Fix Reflux.connectFilter behavior. The result of a filter function must be checked for ```undefined``` or ```null``` but not for boolean. So if I filter some numeric collection in a filter function and return ```0``` the initial state will not be settled.

**Comment by LongLiveCHIEF** [comment]
I'll check this out. Do you have any sample code you'd like to share or gist that will help me dig into this one?

**Comment by mrtho1** [comment]
Just have connectFilter return a falsy value, 0, false, whatever, then pass that state into a component that has a required propType, e.g. React.PropTypes.bool.isRequired.  The react runtime will complain it was not provided.  My hackaround is to return the value wrapped in an array.

**Comment by spoike** [comment]
Seems it will be fixed in PR #371
