### ISSUE TITLE
Reflux mixin initial update

### ISSUE THREAD

**Issue by Aesthetickz** [spoike/refluxjs#323]
When listening from stores or components to stores, the provided mixins don't automatically do an initial action, can this be made optional?

You always have to do like:
this.listenTo(Store, this.onChange);
this.onChange();

or you have to get the store in get Initial state, but that can be cumbersome. The same for the Reflux.connect mixin. Maybe this.listenToAuto(Store, this.onChange)?

**Comment by spoike** [comment]
There is a third parameter:

`this.listenTo(Store, this.onChange, this.onChange);`

The store needs a `getInitialState` method that will be called for the second callback.

**Comment by Aesthetickz** [comment]
Okay, that is fair. But the store will always need the getInitialState then?

**Comment by spoike** [comment]
Oh, I misread your question.

At the current implementation, yes this is the only way.

There has been discussion in the issue tracker about having the store handle a state by itself (e.g. #290). This would in turn make it possible for stores to automatically populate new components based on what has been triggered. Nothing concrete yet.
