### ISSUE TITLE
Debugging store changes

### ISSUE THREAD

**Issue by Dharmoslap** [spoike/refluxjs#326]
Would be great to be able to console.log Store object every time after it's been changed. Or to have console.log for all the actions being triggerd.

**Comment by Dharmoslap** [comment]
The best practice could be mentioned in doc http://stackoverflow.com/questions/30359498/reflux-actions-global-debugging

**Comment by kevinsimper** [comment]
You want something like this, or are you talking about the actions? It could be a good idea with some debugging, but it could be a external plugin first, like a npm package.

```
store.listen(function() {
  console.log(arguments)
})
```

**Comment by Dharmoslap** [comment]
Actions are solved there. :)

**Comment by LongLiveCHIEF** [comment]
Stores are observable, so they're very compatible with your own development needs, such as handling logging, whether it be to the console, or as an application log.

If you think about it, logging is not very different from other sorts of system events and notifications. Javascript itself, and each IDE/dev tool environment has their own way of providing a logging interface, so this would be something you'd want to decide how to implement yourself, not just for Reflux, but for most libraries in the javascript world these days.

I would use @kevinsimper 's solution, or alternatively, if you're using React, you could create a custom `<Log />` component that handles this for you, and you could just listen to whatever store you need to log during an appropriate stage of the `<Log />` component's lifecycel.
