### ISSUE TITLE
Listen on actions from components

### ISSUE THREAD

**Issue by kevinsimper** [spoike/refluxjs#329]
Is is something you should do, or is that a bad pattern?

Like I need to know if a action triggers the `children` `failed` or `completed`, to show some value.

```
AchievementsActions.new.completed.listen(function() {
      // a new
      // Hide the ajax loader
      console.log(arguments)
})
```

**Comment by LongLiveCHIEF** [comment]
I'm not sure what you're asking. Can you try to rephrase?

**Comment by LongLiveCHIEF** [comment]
For questions please use the following communication channels:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

Please only use the [issue tracker](https://github.com/spoike/refluxjs/issues) for bugs and feature requests only.
