### ISSUE TITLE
Invoking the same action in async fashion

### ISSUE THREAD

**Issue by westmark** [spoike/refluxjs#332]
Not sure if I've encountered a bug or if I'm trying to use Reflux in way it wasn't designed to be. Anyway, consider this code

```javascript
var Reflux = require('reflux');

var Actions = Reflux.createActions({
  run: { asyncResult: true }
});


Actions.run.listen(function (index) {
  setTimeout(function () {
    return this.completed(index);
  }.bind(this), index * 1000);
});

Promise.all([Actions.run(1), Actions.run(2), Actions.run(3)])
  .then(function () {
    console.log('Done', ...arguments);
  });
```

So we are running Actions.run three times. The first one will wait one second until calling this.completed, the second two seconds and so on. When running this, the output is 

```
Done [ 1, 1, 1 ]
```

...and the output comes after one second. So it seems that this.completed() will resolve all three promises at once. Is there a way to fix this? I mean, comparing the return values from the three invocations of Actions.run indicates that the promises returned are not just three references to the same promise, so they should be available in there somewhere. Or am I just doing it wrong? :)

**Comment by westmark** [comment]
As soon as you write stuff like the above, just start to think about the issue from another angle; just realized that this would get weird very fast if you have mulitple listen():ers on the same action and all of them calling this.completed(). So... never mind then :)

**Comment by dennisoelkers** [comment]
It still leaves me puzzling. What significance does the parameter to an action have then? It basically means that either:

  1) an action cannot be used in parallel,
  2) the parameter to an action must not have an impact on the result (why can you even have parameters then?)

I do understand the point that any listener to an action can complete/fail this specific execution of the action. This does not mean though, that any listener must be able to complete/fail ANY execution of the action AND determines the result for all executions. What am I missing?
