### ISSUE TITLE
store ES7 decorator helper

### ISSUE THREAD

**Issue by oriSomething** [spoike/refluxjs#333]
this is a proposal for experimental helper to `React.Component`. Because of ES6 classes don't support mixins.
it's in early stages, but the full code for this the is [here](https://gist.github.com/oriSomething/36492428024fb284bcdd).

it suppose to work for component like this:
```javascript
import React, { Component } from 'react';
import store from './store-decorator';
import someStore, { SOME_STORE_SYMBOL } from './some-reflux-store';
 
@store(someStore) 
class SomeComponent extends Component {
  render() {
    return (
      <div>
        {this.state[SOME_STORE_SYMBOL].someProperty}
      </div>
    );
  }
}
```

**Comment by LongLiveCHIEF** [comment]
Reflux and react are not co-dependent upon each other. This wouldn't be a core feature, and is something you'd be able to add on your own.

**Comment by oriSomething** [comment]
hey, i've already done it (and using it). not sure if it's time to publish.

thanks

**Comment by spoike** [comment]
Alternatively, I'd be happy to see if reflux-react extensions are published in a seperate npm package/project.
