### ISSUE TITLE
Difference between listening to actions in componentWillMount and componentDidMount

### ISSUE THREAD

**Issue by jonrh** [spoike/refluxjs#335]
Just quick question, the [Reflux documentation](https://github.com/spoike/refluxjs#react-component-example) states:

*Register your component to listen for changes in your data stores, preferably in the componentDidMount lifecycle method ...*

What is the practical differences between listening to actions in **componentDidMount** as opposed to **componentWillMount**? Alternatively, why is it preferable to do it in *componentDidMount*?

I know *componentWillMount* is called before React renders but I don't see any practical difference between the two.

**Comment by oriSomething** [comment]
if you didn't use `getInitialState` it might save rerender, and `getInitialState` doesn't easy to use in ES6 React component, as in `React.createClass`

**Comment by LongLiveCHIEF** [comment]
For questions please use the following communication channels:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

Please only use the [issue tracker](https://github.com/spoike/refluxjs/issues) for bugs and feature requests only.
