### ISSUE TITLE
Live help sessions?

### ISSUE THREAD

**Issue by cmrnh** [spoike/refluxjs#337]
Hey @spoike + reflux community:

What do you think about setting up regularly-scheduled, live hangouts for helping Reflux users work through integration issues?

The goal is to create an extra layer of support for users who otherwise might open up issues for questions that could be better solved by jumping into a short pair-programming / screenshare session.

It's the kind of thing we do with our students at [Thinkful](http://thinkful.com) and I'd be curious to see if it works outside our walls... We already hold regular sessions on React so it'd be easy to open those up to the broader Reflux community.

Let me know what you think.

**Comment by LongLiveCHIEF** [comment]
There's around the clock live help sessions via the #reflux channel on reactiflux.slack.com:

2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.

I think at the moment, anything more explicit should wait until Reflux is beyond `v0.2.x`
