### ISSUE TITLE
TriggerPromise not working as intended

### ISSUE THREAD

**Issue by achang28** [spoike/refluxjs#351]
My problem is that ".then" method on the promise ( returned from "triggerPromise( )" ) is firing before the promise is being resolved:  See example code below, along with my few comments:

```javascript
'use strict';

var React = require('react-native');
var Reflux = require("reflux");

var Actions = Reflux.createActions({
  "getData": {
    children: ["done", "failed"]
  }
});

var Store = Reflux.createStore({
  listenables: [Actions],
  onGetData: function() {
    // is executing last...
    debugger;
    Actions.getData.done("testing");
  }
})

var {
  AppRegistry,
  Text,
  View,
} = React;

var test = React.createClass({
  render: function() {
    Actions.getData.triggerPromise().then((results) => {
      console.log(results); // is executing first...
      debugger;
    })

    return (
      <View><Text>Testing</Text></View>
    );
  }
});

AppRegistry.registerComponent('test', () => test);
```

**Comment by achang28** [comment]
I am currently using React 0.13.2, and Reflux 0.2.8

**Comment by LongLiveCHIEF** [comment]
This is a problem with your implementation of both actions, and promises. Use one of the help options to resolve this issue:

For questions please use the following communication channels:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

Please only use the [issue tracker](https://github.com/spoike/refluxjs/issues) for bugs and feature requests only.
