### ISSUE TITLE
Question: Listenables, is *on* from onActionName required?

### ISSUE THREAD

**Issue by eek** [spoike/refluxjs#355]
I just noticed that action from store without the on prefix works. on prefix is mandatory or optional while using the `
listenables: [
        HeaderStoreActions
    ]`

The action name is called openSearchMode and it appears I'm not required to name it `onOpenSearchMode(){ ... }` for it to work, `openSearchMode(){ ... }` is sufficient.

**Comment by akre54** [comment]
Yup, you can use either `onFoo` or `foo` as the callback name (see [utils](https://github.com/spoike/refluxjs/blob/v0.2.8/src/utils.js#L43-L45) and [ListenerMethods](https://github.com/spoike/refluxjs/blob/v0.2.8/src/ListenerMethods.js#L80-L81)).

**Comment by eek** [comment]
Awesome! Thanks! :D
