### ISSUE TITLE
Include Action object when it is triggered

### ISSUE THREAD

**Issue by kamijean47** [spoike/refluxjs#365]
refluxjs is interesting so i tried using it

i just noticed something that may be improved, if this actually makes sense

in this sample code:

```javascript
var Actions = Reflux.createActions({
    "load": {async: true}
});

var Store = Reflux.createStore({
    listenables: Actions,
    onLoad: function() {
        // i will do something async here
        dummyAsyncOperation(arguments)
            .then(Actions.load.completed)
            .fail(Actions.load.failed);
    }
});
```
when the promise resolves, i have to call `Actions.load.completed`
i am thinking of having the action itself in the arguments, like:

```javascript
var Store = Reflux.createStore({
    listenables: Actions,
    onLoad: function(action, data) {
        // i will do something async here
        dummyAsyncOperation(data)
            .then(action.completed)
            .fail(action.failed);
    }
});
```

**Comment by spoike** [comment]
Considering the store has a reference to the actions it has registered and every callback is mapped to one action it seems unnecessary (as in the first code snippet). I'd also say it is confusing when the actions uses multiple arguments.

Idk. I'm on the fence on this one.

**Comment by LongLiveCHIEF** [comment]
This is a built in language feature of javascript. Use `this`, or `bind` depending on your implementation details of the calling object.
