### ISSUE TITLE
Higher order components instead of mixins

### ISSUE THREAD

**Issue by juliankrispel** [spoike/refluxjs#366]
Would be nice if reflux also provided methods for wrapping components in higher order components instead of using mixins, since [mixins are on their way out](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750)

**Comment by juliankrispel** [comment]
I'd gladly help implement something like that if @spoike agrees. Shouldn't take long

**Comment by willdady** [comment]
+1

Sounds like the React team have no plans to implement mixins for ES6 style React components so this would be a handy addition to reflux.

**Comment by juliankrispel** [comment]
Closing since this is already ongoing in #293 it seems
