### ISSUE TITLE
Is it possible to create custom sync actions?

### ISSUE THREAD

**Issue by jmca** [spoike/refluxjs#367]
2 questions:
- test1 action: Can you return a value from a synchronous function?
- test2 action: if `{sync: true, children: ['completed']}`, will children be triggered synchronously?

```
var SomeAction = Reflux.createActions({
  test1: {sync: true}
  test2: {sync: true, children: ['completed']}
})

SomeAction.test1.listen(function () {
  //Do some crazy stuff and then return a value for Store to use?
  return 'SOME DATA';
});

SomeAction.test2.listen(function () {
  //Is COMPLETED executed sync or async?
  this.completed('SOMEDATA'); 
});
```

**Comment by spoike** [comment]
Please use proper communications channels for questions about reflux, such as:

1. [StackOverflow with the `refluxjs` tag](http://stackoverflow.com/questions/tagged/refluxjs)
2. [`#reflux` channel](https://reactiflux.slack.com/messages/reflux/) on Reactiflux Slack group. [Sign up here](http://reactiflux.com/) for an account.
3. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/spoike/refluxjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
4. [![Thinkful](https://tf-assets-staging.s3.amazonaws.com/badges/thinkful_repo_badge.svg)](http://start.thinkful.com/react/?utm_source=github&utm_medium=badge&utm_campaign=reflux)
