### ISSUE TITLE
"[object Object] is missing a listen method" in store when listening to other store

### ISSUE THREAD

**Issue by filiptc** [spoike/refluxjs#370]
The following code throws `[object Object] is missing a listen method` on the `listenTo` line. I've lost a couple hours with this and would swear I've been following the readme.

```javascript
var MyOtherStore = Reflux.createStore({
  listenables: [...],
 ...handlers...
}
```
```javascript
var MyStore = Reflux.createStore({
  init: function () {
    this.listenTo(require('./MyOtherStore'), this.handleChange);
  },
  handleChange: function (stuff) {
    console.log(stuff);
  }
}
```

Thanks!

**Comment by spoike** [comment]
Are you sure you've exported the store properly? I.e:

```
// your store impl.

module.exports = MyOtherStore;
```

**Comment by filiptc** [comment]
I recently switched to ES2015 syntax and am transpiling with Babel in a browserify environment and problems might indeed be related to buggy imports. Are there any known issues with babel + browserify?

**Comment by filiptc** [comment]
It's strange because all my other imports work perfectly, but the imported stores are just empty objects when using `require` and undefined when using `import`.

**Comment by filiptc** [comment]
I found the issue: I had a circular dependency creating a deadlock. In my case I had.
```javascript
var MyOtherStore = Reflux.createStore({
  init: function () {
    this.listenTo(require('./MyStore'), this.handleChange);
  },
  handleChange: function (stuff) {
    console.log(stuff);
  }
}
```
```javascript
var MyStore = Reflux.createStore({
  init: function () {
    this.listenTo(require('./MyOtherStore'), this.handleChange);
  },
  handleChange: function (stuff) {
    console.log(stuff);
  }
}
```
Even though this seems like really obvious, within a complex architecture it's easily overseen. Maybe it should be hinted on in the docs...
