### ISSUE TITLE
Callback after store is updated

### ISSUE THREAD

**Issue by Dharmoslap** [spoike/refluxjs#373]
I need to run a callback every time action is called and store is updated. But I need to get whole store as argument. There is 'output' callback, but the whole store is not reachable from there.

More here:
http://stackoverflow.com/questions/31452646/reflux-callback-after-store-is-changed

**Comment by oriSomething** [comment]
why `Store#trigger()` is not enough?

**Comment by Dharmoslap** [comment]
Maybe it is enough, but from docs it seems like Store#trigger() can listen just to Reflux actions.

**Comment by spoike** [comment]
Why not create a join with the action and store? Something like this:

```
function after(action, store, cb) {
    var join = Reflux.joinTrailing(action, store);
    join.listen(function(actionArgs, storeArgs) {
        cb(store /*, and whatever you need from actionArgs and storeArgs */);
    });
    return join;
}

// Usage:
var a = after(myAction, myStore, myCallback);
// don't forget to unsubscribe "a" if you don't need it
```

**Comment by Dharmoslap** [comment]
But then I have to subscribe it to all actions.
