### ISSUE TITLE
action with asyncResult: true does not return promise in IE11

### ISSUE THREAD

**Issue by jimmyn** [spoike/refluxjs#376]
It seems like IE is buggy as allways. It doesnt return promise from actions resolved with child actions like this:

```javascript
// Create async action with `completed` & `failed` children
var makeRequest = Reflux.createAction({ asyncResult: true });

var RequestStore = Reflux.createStore({
    init: function() {
        this.listenTo(makeRequest, 'onMakeRequest');
    },

    onMakeRequest: function(url) {
        // Assume `request` is some HTTP library (e.g. superagent)
        request(url, function(response) {
            if (response.ok) {
                makeRequest.completed(response.body);
            } else {
                makeRequest.failed(response.error);
            }
        })
    }
});
```

Instead in returns undefined

**Comment by LongLiveCHIEF** [comment]
can you include the full error message?

**Comment by jimmyn** [comment]
There is no error message at all. Action just returns undefined instead of promise.

**Comment by LongLiveCHIEF** [comment]
I'm sorry, but without something more to go on, this is too vague to dig in and help. There is no defined `Action` object in the public API of reflux, so if you use  `Action` in any expression, I would expect it to either return undefined or stop execution with an `Action is undefined` message in your console, depending on your code.

**Comment by jimmyn** [comment]
Here is the example of my code

```
Actions.Me = Reflux.createActions
  fetch: asyncResult: true

Stores.Me = Reflux.createStore
  listenables: Actions.Me

  fetch: ->
     currentUser = new Models.CurrentUser
     req = currentUser.fetch()
     req.done ->
        Actions.Me.fetch.completed()
      req.fail (data) ->
        Actions.Me.fetch.failed(data)
```
currentUser here is a Backbone model and req is a jQuery jqXHR object
In all browsers except IE  ``Actions.Me.fetch()`` returns native Promise object so I can do something like
```
Actions.Me.fetch().then doSomething
```
But in IE it returns ``undefined`` so I'm getting the error
```
Unable to get property 'then' of undefined or null reference
```

**Comment by jimmyn** [comment]
Ok it seems like IE doesn't support promises at all =(

**Comment by LongLiveCHIEF** [comment]
Promises aren't native to .js, so you have to implement support for them yourself.
