### ISSUE TITLE
For dist rather make eventemitter3 a bower dependency

### ISSUE THREAD

**Issue by clintwood** [spoike/refluxjs#377]
For projects that already have `eventemitter3` as a dependency the duplication in the distribution is unnecessary.  Wouldn't it rather make sense to make it a dependency in `bower.json`?

Great Flux implementation, thank you!

**Comment by LongLiveCHIEF** [comment]
Great question.  There are some really good reasons why we'd still want to leave it as a reflux dependency. Here are a few of the most important ones:<sup>see note</sup>

- Everyone has their own opinions of which dependency manager they prefer, so we can't rely on consumers implementing our dependencies
- We're working to make reflux isomorphic, and Bower is more of a browser-based tool
- Our internal code might need to support a different version of the eventemitter dependency, and allowing the version implementation decision up to the consumer could break your reflux implementation
- All dependency management tools start with the assumption that every dependency lists it's own dependencies. What happens next, is handled differently by each dependency manager, depending on the technique they use to implement the module pattern (AMD, UMD, CommonJS). This assumption can come to be very important to library creators in their code design, so they have "control" of the execution environment downstream (in other words, they have the ability to know how it *should* work after released into the wild)

**Comment by LongLiveCHIEF** [comment]
><sup>see note</sup>

Forgot the note!  

Note: We're working to keep reflux as lean as possible. Future versions of Reflux may or may not depend the eventemitter3 module, either explicitly or as an optional/peer.

**Comment by clintwood** [comment]
@LongLiveCHIEF, I hear you and all your points are valid.  My concern is size and I think EE adds about 2k minified (maybe just under) to Reflux and in my case it will be duplicated.  I guess I'll pull the src from the node_modules in my build process and avoid the bower dist...  I wonder what other people are doing to dedup deps?  Also perhaps browserify will dedup... I'll experiment!  

Thanks for taking the time to respond!

**Comment by clintwood** [comment]
@LongLiveCHIEF, resolved for my use case!  FWIW for others who want to dedup EE3 I did the following:

- Removed `reflux` dep from my local projects `bower.json`
- Made sure `eventemitter3` was a dep in `bower.json`
- Also in `bower.json` changed `"ignore": ["node_modules", ...]` to `"ignore": ["node_modules/*", "!node_modules/reflux", ...]`
- Put `reflux` in `devDependencies` for my node projects `package.json`
- Required it wherever I needed it in src files like this `var reflux = require('reflux');` (actually I'm using ES2015/6 doing `import * as reflux from 'reflux';`)
- Used `browserify` to bundle src files
- Made a **big fat project note** that this dep had to be in `package.json` and **_not_** in `bower.json`

All happy now!
